package aero.pilotlog.databases.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import aero.pilotlog.databases.entities.Qualification;
import aero.pilotlog.databases.entities.SettingUserAccount;
import aero.pilotlog.databases.entities.Aircraft;
import aero.pilotlog.databases.entities.Airfield;
import aero.pilotlog.databases.entities.AllowanceRules;
import aero.pilotlog.databases.entities.BackupDB;
import aero.pilotlog.databases.entities.Duty;
import aero.pilotlog.databases.entities.Expense;
import aero.pilotlog.databases.entities.Flight;
import aero.pilotlog.databases.entities.ImagePic;
import aero.pilotlog.databases.entities.LimitRules;
import aero.pilotlog.databases.entities.Pilot;
import aero.pilotlog.databases.entities.RecordDelete;
import aero.pilotlog.databases.entities.SettingConfig;
import aero.pilotlog.databases.entities.SettingLocal;
import aero.pilotlog.databases.entities.ValidationRules;
import aero.pilotlog.databases.entities.Weather;
import aero.pilotlog.databases.entities.WeatherAF;
import aero.pilotlog.databases.entities.MyQuery;
import aero.pilotlog.databases.entities.MyQueryBuild;
import aero.pilotlog.databases.entities.WeatherLocal;
import aero.pilotlog.databases.entities.ZAircraftMake;
import aero.pilotlog.databases.entities.ZApproach;
import aero.pilotlog.databases.entities.ZApproachCat;
import aero.pilotlog.databases.entities.ZCountry;
import aero.pilotlog.databases.entities.ZCurrency;
import aero.pilotlog.databases.entities.ZDelay;
import aero.pilotlog.databases.entities.ZDelayGroup;
import aero.pilotlog.databases.entities.ZExpense;
import aero.pilotlog.databases.entities.ZExpenseGroup;
import aero.pilotlog.databases.entities.ZFNPT;
import aero.pilotlog.databases.entities.ZLaunch;
import aero.pilotlog.databases.entities.ZLimit;
import aero.pilotlog.databases.entities.ZOperation;
import aero.pilotlog.databases.entities.ZPackage;
import aero.pilotlog.databases.entities.ZQualification;
import aero.pilotlog.databases.entities.ZTimeZone;
import aero.pilotlog.databases.entities.ZTimeZoneDST;
import aero.pilotlog.databases.entities.ZValidation;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig aircraftDaoConfig;
    private final DaoConfig airfieldDaoConfig;
    private final DaoConfig allowanceRulesDaoConfig;
    private final DaoConfig backupDBDaoConfig;
    private final DaoConfig dutyDaoConfig;
    private final DaoConfig expenseDaoConfig;
    private final DaoConfig flightDaoConfig;
    private final DaoConfig imagePicDaoConfig;
    private final DaoConfig limitRulesDaoConfig;
    private final DaoConfig pilotDaoConfig;
    private final DaoConfig recordDeleteDaoConfig;
    private final DaoConfig settingConfigDaoConfig;
    private final DaoConfig settingLocalDaoConfig;
    private final DaoConfig settingUserAccountDaoConfig;
    private final DaoConfig validationRulesDaoConfig;
    private final DaoConfig weatherDaoConfig;
    private final DaoConfig weatherAFDaoConfig;
    private final DaoConfig myQueryDaoConfig;
    private final DaoConfig myQueryBuildDaoConfig;
    private final DaoConfig zAircraftMakeDaoConfig;
    private final DaoConfig zApproachDaoConfig;
    private final DaoConfig zApproachCatDaoConfig;
    private final DaoConfig zCountryDaoConfig;
    private final DaoConfig zCurrencyDaoConfig;
    private final DaoConfig zDelayDaoConfig;
    private final DaoConfig zDelayGroupDaoConfig;
    private final DaoConfig zLaunchDaoConfig;
    private final DaoConfig zOperationDaoConfig;
    private final DaoConfig zPackageDaoConfig;
    private final DaoConfig zTimeZoneDaoConfig;
    private final DaoConfig zTimeZoneDSTDaoConfig;
    private final DaoConfig zValidationDaoConfig;
    private final DaoConfig zFNPTDaoConfig;
    private final DaoConfig zLimitDaoConfig;
    private final DaoConfig zExpenseDaoConfig;
    private final DaoConfig zExpenseGroupDaoConfig;
    private final DaoConfig qualificationDaoConfig;
    private final DaoConfig zQualificationDaoConfig;
    private final DaoConfig weatherLocalDaoConfig;


    private final AircraftDao aircraftDao;
    private final AirfieldDao airfieldDao;
    private final AllowanceRulesDao allowanceRulesDao;
    private final BackupDBDao backupDBDao;
    private final DutyDao dutyDao;
    private final ExpenseDao expenseDao;
    private final FlightDao flightDao;
    private final ImagePicDao imagePicDao;
    private final LimitRulesDao limitRulesDao;
    private final PilotDao pilotDao;
    private final RecordDeleteDao recordDeleteDao;
    private final SettingConfigDao settingConfigDao;
    private final SettingLocalDao settingLocalDao;
    private final SettingUserAccountDao settingUserAccountDao;
    private final ValidationRulesDao validationRulesDao;
    private final WeatherDao weatherDao;
    private final WeatherAFDao weatherAFDao;
    private final MyQueryDao myQueryDao;
    private final MyQueryBuildDao myQueryBuildDao;
    private final ZAircraftMakeDao zAircraftMakeDao;
    private final ZApproachDao zApproachDao;
    private final ZApproachCatDao zApproachCatDao;
    private final ZCountryDao zCountryDao;
    private final ZCurrencyDao zCurrencyDao;
    private final ZDelayDao zDelayDao;
    private final ZDelayGroupDao zDelayGroupDao;
    private final ZLaunchDao zLaunchDao;
    private final ZOperationDao zOperationDao;
    private final ZPackageDao zPackageDao;
    private final ZTimeZoneDao zTimeZoneDao;
    private final ZTimeZoneDSTDao zTimeZoneDSTDao;
    private final ZValidationDao zValidationDao;
    private final ZFNPTDao zFNPTDao;
    private final ZLimitDao zLimitDao;
    private final ZExpenseDao zExpenseDao;
    private final ZExpenseGroupDao zExpenseGroupDao;
    private final QualificationDao qualificationDao;
    private final ZQualificationDao zQualificationDao;
    private final WeatherLocalDao weatherLocalDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        aircraftDaoConfig = daoConfigMap.get(AircraftDao.class).clone();
        aircraftDaoConfig.initIdentityScope(type);

        airfieldDaoConfig = daoConfigMap.get(AirfieldDao.class).clone();
        airfieldDaoConfig.initIdentityScope(type);

        allowanceRulesDaoConfig = daoConfigMap.get(AllowanceRulesDao.class).clone();
        allowanceRulesDaoConfig.initIdentityScope(type);

        backupDBDaoConfig = daoConfigMap.get(BackupDBDao.class).clone();
        backupDBDaoConfig.initIdentityScope(type);

        dutyDaoConfig = daoConfigMap.get(DutyDao.class).clone();
        dutyDaoConfig.initIdentityScope(type);

        expenseDaoConfig = daoConfigMap.get(ExpenseDao.class).clone();
        expenseDaoConfig.initIdentityScope(type);

        flightDaoConfig = daoConfigMap.get(FlightDao.class).clone();
        flightDaoConfig.initIdentityScope(type);

        imagePicDaoConfig = daoConfigMap.get(ImagePicDao.class).clone();
        imagePicDaoConfig.initIdentityScope(type);

        limitRulesDaoConfig = daoConfigMap.get(LimitRulesDao.class).clone();
        limitRulesDaoConfig.initIdentityScope(type);

        pilotDaoConfig = daoConfigMap.get(PilotDao.class).clone();
        pilotDaoConfig.initIdentityScope(type);

        recordDeleteDaoConfig = daoConfigMap.get(RecordDeleteDao.class).clone();
        recordDeleteDaoConfig.initIdentityScope(type);

        settingConfigDaoConfig = daoConfigMap.get(SettingConfigDao.class).clone();
        settingConfigDaoConfig.initIdentityScope(type);

        settingLocalDaoConfig = daoConfigMap.get(SettingLocalDao.class).clone();
        settingLocalDaoConfig.initIdentityScope(type);

        settingUserAccountDaoConfig = daoConfigMap.get(SettingUserAccountDao.class).clone();
        settingUserAccountDaoConfig.initIdentityScope(type);

        validationRulesDaoConfig = daoConfigMap.get(ValidationRulesDao.class).clone();
        validationRulesDaoConfig.initIdentityScope(type);

        weatherDaoConfig = daoConfigMap.get(WeatherDao.class).clone();
        weatherDaoConfig.initIdentityScope(type);

        weatherAFDaoConfig = daoConfigMap.get(WeatherAFDao.class).clone();
        weatherAFDaoConfig.initIdentityScope(type);

        myQueryDaoConfig = daoConfigMap.get(MyQueryDao.class).clone();
        myQueryDaoConfig.initIdentityScope(type);

        myQueryBuildDaoConfig = daoConfigMap.get(MyQueryBuildDao.class).clone();
        myQueryBuildDaoConfig.initIdentityScope(type);

        zAircraftMakeDaoConfig = daoConfigMap.get(ZAircraftMakeDao.class).clone();
        zAircraftMakeDaoConfig.initIdentityScope(type);

        zApproachDaoConfig = daoConfigMap.get(ZApproachDao.class).clone();
        zApproachDaoConfig.initIdentityScope(type);

        zApproachCatDaoConfig = daoConfigMap.get(ZApproachCatDao.class).clone();
        zApproachCatDaoConfig.initIdentityScope(type);

        zCountryDaoConfig = daoConfigMap.get(ZCountryDao.class).clone();
        zCountryDaoConfig.initIdentityScope(type);

        zCurrencyDaoConfig = daoConfigMap.get(ZCurrencyDao.class).clone();
        zCurrencyDaoConfig.initIdentityScope(type);

        zDelayDaoConfig = daoConfigMap.get(ZDelayDao.class).clone();
        zDelayDaoConfig.initIdentityScope(type);

        zDelayGroupDaoConfig = daoConfigMap.get(ZDelayGroupDao.class).clone();
        zDelayGroupDaoConfig.initIdentityScope(type);


        zFNPTDaoConfig = daoConfigMap.get(ZFNPTDao.class).clone();
        zFNPTDaoConfig.initIdentityScope(type);

        zLaunchDaoConfig = daoConfigMap.get(ZLaunchDao.class).clone();
        zLaunchDaoConfig.initIdentityScope(type);

        zOperationDaoConfig = daoConfigMap.get(ZOperationDao.class).clone();
        zOperationDaoConfig.initIdentityScope(type);

        zPackageDaoConfig = daoConfigMap.get(ZPackageDao.class).clone();
        zPackageDaoConfig.initIdentityScope(type);

        zTimeZoneDaoConfig = daoConfigMap.get(ZTimeZoneDao.class).clone();
        zTimeZoneDaoConfig.initIdentityScope(type);

        zTimeZoneDSTDaoConfig = daoConfigMap.get(ZTimeZoneDSTDao.class).clone();
        zTimeZoneDSTDaoConfig.initIdentityScope(type);

        zValidationDaoConfig = daoConfigMap.get(ZValidationDao.class).clone();
        zValidationDaoConfig.initIdentityScope(type);

        zLimitDaoConfig = daoConfigMap.get(ZLimitDao.class).clone();
        zLimitDaoConfig.initIdentityScope(type);

        zExpenseDaoConfig = daoConfigMap.get(ZExpenseDao.class).clone();
        zExpenseDaoConfig.initIdentityScope(type);

        zExpenseGroupDaoConfig = daoConfigMap.get(ZExpenseGroupDao.class).clone();
        zExpenseGroupDaoConfig.initIdentityScope(type);

        qualificationDaoConfig = daoConfigMap.get(QualificationDao.class).clone();
        qualificationDaoConfig.initIdentityScope(type);

        zQualificationDaoConfig = daoConfigMap.get(ZQualificationDao.class).clone();
        zQualificationDaoConfig.initIdentityScope(type);

        weatherLocalDaoConfig = daoConfigMap.get(WeatherLocalDao.class).clone();
        weatherLocalDaoConfig.initIdentityScope(type);

        aircraftDao = new AircraftDao(aircraftDaoConfig, this);
        airfieldDao = new AirfieldDao(airfieldDaoConfig, this);
        allowanceRulesDao = new AllowanceRulesDao(allowanceRulesDaoConfig, this);
        backupDBDao = new BackupDBDao(backupDBDaoConfig, this);
        dutyDao = new DutyDao(dutyDaoConfig, this);
        expenseDao = new ExpenseDao(expenseDaoConfig, this);
        flightDao = new FlightDao(flightDaoConfig, this);
        imagePicDao = new ImagePicDao(imagePicDaoConfig, this);
        limitRulesDao = new LimitRulesDao(limitRulesDaoConfig, this);
        pilotDao = new PilotDao(pilotDaoConfig, this);
        recordDeleteDao = new RecordDeleteDao(recordDeleteDaoConfig, this);
        settingConfigDao = new SettingConfigDao(settingConfigDaoConfig, this);
        settingLocalDao = new SettingLocalDao(settingLocalDaoConfig, this);
        settingUserAccountDao = new SettingUserAccountDao(settingUserAccountDaoConfig, this);
        validationRulesDao = new ValidationRulesDao(validationRulesDaoConfig, this);
        weatherDao = new WeatherDao(weatherDaoConfig, this);
        weatherAFDao = new WeatherAFDao(weatherAFDaoConfig, this);
        myQueryDao = new MyQueryDao(myQueryDaoConfig, this);
        myQueryBuildDao = new MyQueryBuildDao(myQueryBuildDaoConfig, this);
        zAircraftMakeDao = new ZAircraftMakeDao(zAircraftMakeDaoConfig, this);
        zApproachDao = new ZApproachDao(zApproachDaoConfig, this);
        zApproachCatDao = new ZApproachCatDao(zApproachCatDaoConfig, this);
        zCountryDao = new ZCountryDao(zCountryDaoConfig, this);
        zCurrencyDao = new ZCurrencyDao(zCurrencyDaoConfig, this);
        zDelayDao = new ZDelayDao(zDelayDaoConfig, this);
        zDelayGroupDao = new ZDelayGroupDao(zDelayGroupDaoConfig, this);
        zFNPTDao = new ZFNPTDao(zFNPTDaoConfig, this);
        zLaunchDao = new ZLaunchDao(zLaunchDaoConfig, this);
        zOperationDao = new ZOperationDao(zOperationDaoConfig, this);
        zPackageDao = new ZPackageDao(zPackageDaoConfig, this);
        zTimeZoneDao = new ZTimeZoneDao(zTimeZoneDaoConfig, this);
        zTimeZoneDSTDao = new ZTimeZoneDSTDao(zTimeZoneDSTDaoConfig, this);
        zValidationDao = new ZValidationDao(zValidationDaoConfig, this);
        zLimitDao = new ZLimitDao(zLimitDaoConfig, this);
        zExpenseDao = new ZExpenseDao(zExpenseDaoConfig, this);
        zExpenseGroupDao = new ZExpenseGroupDao(zExpenseGroupDaoConfig, this);
        qualificationDao = new QualificationDao(qualificationDaoConfig, this);
        zQualificationDao = new ZQualificationDao(zQualificationDaoConfig, this);
        weatherLocalDao = new WeatherLocalDao(weatherLocalDaoConfig, this);

        registerDao(Aircraft.class, aircraftDao);
        registerDao(Airfield.class, airfieldDao);
        registerDao(AllowanceRules.class, allowanceRulesDao);
        registerDao(BackupDB.class, backupDBDao);
        registerDao(Duty.class, dutyDao);
        registerDao(Expense.class, expenseDao);
        registerDao(Flight.class, flightDao);
        registerDao(ImagePic.class, imagePicDao);
        registerDao(LimitRules.class, limitRulesDao);
        registerDao(Pilot.class, pilotDao);
        registerDao(RecordDelete.class, recordDeleteDao);
        registerDao(SettingConfig.class, settingConfigDao);
        registerDao(SettingLocal.class, settingLocalDao);
        registerDao(SettingUserAccount.class, settingUserAccountDao);
        registerDao(ValidationRules.class, validationRulesDao);
        registerDao(Weather.class, weatherDao);
        registerDao(WeatherAF.class, weatherAFDao);
        registerDao(MyQuery.class, myQueryDao);
        registerDao(MyQueryBuild.class, myQueryBuildDao);
        registerDao(ZAircraftMake.class, zAircraftMakeDao);
        registerDao(ZApproach.class, zApproachDao);
        registerDao(ZApproachCat.class, zApproachCatDao);
        registerDao(ZCountry.class, zCountryDao);
        registerDao(ZCurrency.class, zCurrencyDao);
        registerDao(ZDelay.class, zDelayDao);
        registerDao(ZDelayGroup.class, zDelayGroupDao);
        registerDao(ZFNPT.class, zFNPTDao);
        registerDao(ZLaunch.class, zLaunchDao);
        registerDao(ZOperation.class, zOperationDao);
        registerDao(ZPackage.class, zPackageDao);
        registerDao(ZTimeZone.class, zTimeZoneDao);
        registerDao(ZTimeZoneDST.class, zTimeZoneDSTDao);
        registerDao(ZValidation.class, zValidationDao);
        registerDao(ZLimit.class, zLimitDao);
        registerDao(ZExpense.class, zExpenseDao);
        registerDao(ZExpenseGroup.class, zExpenseGroupDao);
        registerDao(Qualification.class, qualificationDao);
        registerDao(ZQualification.class, zQualificationDao);
        registerDao(WeatherLocal.class, weatherLocalDao);
    }
    
    public void clear() {
        aircraftDaoConfig.getIdentityScope().clear();
        airfieldDaoConfig.getIdentityScope().clear();
        allowanceRulesDaoConfig.getIdentityScope().clear();
        backupDBDaoConfig.getIdentityScope().clear();
        dutyDaoConfig.getIdentityScope().clear();
        expenseDaoConfig.getIdentityScope().clear();
        flightDaoConfig.getIdentityScope().clear();
        imagePicDaoConfig.getIdentityScope().clear();
        limitRulesDaoConfig.getIdentityScope().clear();
        pilotDaoConfig.getIdentityScope().clear();
        recordDeleteDaoConfig.getIdentityScope().clear();
        settingConfigDaoConfig.getIdentityScope().clear();
        settingLocalDaoConfig.getIdentityScope().clear();
        settingUserAccountDaoConfig.getIdentityScope().clear();
        validationRulesDaoConfig.getIdentityScope().clear();
        weatherDaoConfig.getIdentityScope().clear();
        weatherAFDaoConfig.getIdentityScope().clear();
        myQueryDaoConfig.getIdentityScope().clear();
        myQueryBuildDaoConfig.getIdentityScope().clear();
        zAircraftMakeDaoConfig.getIdentityScope().clear();
        zApproachDaoConfig.getIdentityScope().clear();
        zApproachCatDaoConfig.getIdentityScope().clear();
        zCountryDaoConfig.getIdentityScope().clear();
        zCurrencyDaoConfig.getIdentityScope().clear();
        zDelayDaoConfig.getIdentityScope().clear();
        zDelayGroupDaoConfig.getIdentityScope().clear();
        zFNPTDaoConfig.getIdentityScope().clear();
        zLaunchDaoConfig.getIdentityScope().clear();
        zOperationDaoConfig.getIdentityScope().clear();
        zPackageDaoConfig.getIdentityScope().clear();
        zTimeZoneDaoConfig.getIdentityScope().clear();
        zTimeZoneDSTDaoConfig.getIdentityScope().clear();
        zValidationDaoConfig.getIdentityScope().clear();
        zLimitDaoConfig.getIdentityScope().clear();
        zExpenseDaoConfig.getIdentityScope().clear();
        zExpenseGroupDaoConfig.getIdentityScope().clear();
        qualificationDaoConfig.getIdentityScope().clear();
        zQualificationDaoConfig.getIdentityScope().clear();
        weatherLocalDaoConfig.getIdentityScope().clear();
    }

    public AircraftDao getAircraftDao() {
        return aircraftDao;
    }

    public AirfieldDao getAirfieldDao() {
        return airfieldDao;
    }

    public AllowanceRulesDao getAllowanceRulesDao() {
        return allowanceRulesDao;
    }

    public BackupDBDao getBackupDBDao() {
        return backupDBDao;
    }

    public DutyDao getDutyDao() {
        return dutyDao;
    }

    public ExpenseDao getExpenseDao() {
        return expenseDao;
    }

    public FlightDao getFlightDao() {
        return flightDao;
    }

    public ImagePicDao getImagePicDao() {
        return imagePicDao;
    }

    public LimitRulesDao getLimitRulesDao() {
        return limitRulesDao;
    }

    public PilotDao getPilotDao() {
        return pilotDao;
    }

    public RecordDeleteDao getRecordDeleteDao() {
        return recordDeleteDao;
    }

    public SettingConfigDao getSettingConfigDao() {
        return settingConfigDao;
    }

    public SettingLocalDao getSettingLocalDao() {
        return settingLocalDao;
    }

    public SettingUserAccountDao getSettingUserAccountDao() {
        return settingUserAccountDao;
    }

    public ValidationRulesDao getValidationRulesDao() {
        return validationRulesDao;
    }

    public WeatherDao getWeatherDao() {
        return weatherDao;
    }

    public WeatherAFDao getWeatherAFDao() {
        return weatherAFDao;
    }

    public MyQueryDao getMyQueryDao() {
        return myQueryDao;
    }

    public MyQueryBuildDao getMyQueryBuildDao() {
        return myQueryBuildDao;
    }

    public ZAircraftMakeDao getZAircraftMakeDao() {
        return zAircraftMakeDao;
    }

    public ZApproachDao getZApproachDao() {
        return zApproachDao;
    }

    public ZApproachCatDao getZApproachCatDao() {
        return zApproachCatDao;
    }

    public ZCountryDao getZCountryDao() {
        return zCountryDao;
    }

    public ZCurrencyDao getZCurrencyDao() {
        return zCurrencyDao;
    }

    public ZDelayDao getZDelayDao() {
        return zDelayDao;
    }

    public ZDelayGroupDao getZDelayGroupDao() {
        return zDelayGroupDao;
    }

    public ZFNPTDao getZFNPTDao() {
        return zFNPTDao;
    }

    public ZLaunchDao getZLaunchDao() {
        return zLaunchDao;
    }

    public ZOperationDao getZOperationDao() {
        return zOperationDao;
    }

    public ZPackageDao getZPackageDao() {
        return zPackageDao;
    }

    public ZTimeZoneDao getZTimeZoneDao() {
        return zTimeZoneDao;
    }

    public ZTimeZoneDSTDao getZTimeZoneDSTDao() {
        return zTimeZoneDSTDao;
    }

    public ZValidationDao getZValidationDao() {
        return zValidationDao;
    }

    public ZLimitDao getZLimitDao() {
        return zLimitDao;
    }

    public ZExpenseDao getZExpenseDao() {
        return zExpenseDao;
    }

    public ZExpenseGroupDao getZExpenseGroupDao() {
        return zExpenseGroupDao;
    }

    public QualificationDao getQualificationDao() {
        return qualificationDao;
    }

    public ZQualificationDao getZQualificationDao() {
        return zQualificationDao;
    }

    public WeatherLocalDao getWeatherLocalDao() {
        return weatherLocalDao;
    }
}
