package aero.pilotlog.databases.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import aero.pilotlog.databases.entities.Weather;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table WEATHER.
*/
public class WeatherDao extends AbstractDao<Weather, byte[]> {

    public static final String TABLENAME = "WEATHER";

    /**
     * Properties of entity Weather.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property WxCode = new Property(0, byte[].class, "WxCode", true, "WXCODE");
        public final static Property WxRoute = new Property(1, String.class, "WxRoute", false, "WXROUTE");
        public final static Property Record_Modified = new Property(2, Long.class, "Record_Modified", false, "RECORD_MODIFIED");
        public final static Property Record_Upload = new Property(3, Boolean.class, "Record_Upload", false, "RECORD_UPLOAD");
    };


    public WeatherDao(DaoConfig config) {
        super(config);
    }
    
    public WeatherDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'WEATHER' (" + //
                "'WXCODE' BLOB PRIMARY KEY ," + // 0: WxCode
                "'WXROUTE' TEXT," + // 1: WxRoute
                "'RECORD_MODIFIED' INTEGER," + // 2: Record_Modified
                "'RECORD_UPLOAD' INTEGER);"); // 3: Record_Upload
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'WEATHER'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Weather entity) {
        stmt.clearBindings();
 
        byte[] WxCode = entity.getWxCode();
        if (WxCode != null) {
            stmt.bindBlob(1, WxCode);
        }
 
        String WxRoute = entity.getWxRoute();
        if (WxRoute != null) {
            stmt.bindString(2, WxRoute);
        }
 
        Long Record_Modified = entity.getRecord_Modified();
        if (Record_Modified != null) {
            stmt.bindLong(3, Record_Modified);
        }
 
        Boolean Record_Upload = entity.getRecord_Upload();
        if (Record_Upload != null) {
            stmt.bindLong(4, Record_Upload ? 1l: 0l);
        }
    }

    /** @inheritdoc */
    @Override
    public byte[] readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getBlob(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Weather readEntity(Cursor cursor, int offset) {
        Weather entity = new Weather( //
            cursor.isNull(offset + 0) ? null : cursor.getBlob(offset + 0), // WxCode
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // WxRoute
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // Record_Modified
            cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0 // Record_Upload
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Weather entity, int offset) {
        entity.setWxCode(cursor.isNull(offset + 0) ? null : cursor.getBlob(offset + 0));
        entity.setWxRoute(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setRecord_Modified(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setRecord_Upload(cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected byte[] updateKeyAfterInsert(Weather entity, long rowId) {
        return entity.getWxCode();
    }
    
    /** @inheritdoc */
    @Override
    public byte[] getKey(Weather entity) {
        if(entity != null) {
            return entity.getWxCode();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
