package aero.pilotlog.databases.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import aero.pilotlog.databases.entities.ZDelay;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table ZDELAY.
*/
public class ZDelayDao extends AbstractDao<ZDelay, Integer> {

    public static final String TABLENAME = "ZDELAY";

    /**
     * Properties of entity ZDelay.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property DelayCode = new Property(0, Integer.class, "DelayCode", true, "DELAYCODE");
        public final static Property DelayDD = new Property(1, String.class, "DelayDD", false, "DELAYDD");
        public final static Property DelayShort = new Property(2, String.class, "DelayShort", false, "DELAYSHORT");
        public final static Property DelayLong = new Property(3, String.class, "DelayLong", false, "DELAYLONG");
        public final static Property DelayGroupCode = new Property(4, Integer.class, "DelayGroupCode", false, "DELAYGROUPCODE");
        public final static Property Record_Modified = new Property(5, Long.class, "Record_Modified", false, "RECORD_MODIFIED");
    };


    public ZDelayDao(DaoConfig config) {
        super(config);
    }
    
    public ZDelayDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'ZDELAY' (" + //
                "'DELAYCODE' INTEGER PRIMARY KEY ," + // 0: DelayCode
                "'DELAYDD' TEXT," + // 1: DelayDD
                "'DELAYSHORT' TEXT," + // 2: DelayShort
                "'DELAYLONG' TEXT," + // 3: DelayLong
                "'DELAYGROUPCODE' INTEGER," + // 4: DelayGroupCode
                "'RECORD_MODIFIED' INTEGER);"); // 5: Record_Modified
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'ZDELAY'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ZDelay entity) {
        stmt.clearBindings();
 
        Integer DelayCode = entity.getDelayCode();
        if (DelayCode != null) {
            stmt.bindLong(1, DelayCode);
        }
 
        String DelayDD = entity.getDelayDD();
        if (DelayDD != null) {
            stmt.bindString(2, DelayDD);
        }
 
        String DelayShort = entity.getDelayShort();
        if (DelayShort != null) {
            stmt.bindString(3, DelayShort);
        }
 
        String DelayLong = entity.getDelayLong();
        if (DelayLong != null) {
            stmt.bindString(4, DelayLong);
        }
 
        Integer DelayGroupCode = entity.getDelayGroupCode();
        if (DelayGroupCode != null) {
            stmt.bindLong(5, DelayGroupCode);
        }
 
        Long Record_Modified = entity.getRecord_Modified();
        if (Record_Modified != null) {
            stmt.bindLong(6, Record_Modified);
        }
    }

    /** @inheritdoc */
    @Override
    public Integer readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getInt(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public ZDelay readEntity(Cursor cursor, int offset) {
        ZDelay entity = new ZDelay( //
            cursor.isNull(offset + 0) ? null : cursor.getInt(offset + 0), // DelayCode
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // DelayDD
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // DelayShort
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // DelayLong
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // DelayGroupCode
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5) // Record_Modified
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ZDelay entity, int offset) {
        entity.setDelayCode(cursor.isNull(offset + 0) ? null : cursor.getInt(offset + 0));
        entity.setDelayDD(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDelayShort(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDelayLong(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setDelayGroupCode(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setRecord_Modified(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Integer updateKeyAfterInsert(ZDelay entity, long rowId) {
        return entity.getDelayCode();
    }
    
    /** @inheritdoc */
    @Override
    public Integer getKey(ZDelay entity) {
        if(entity != null) {
            return entity.getDelayCode();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
