package aero.pilotlog.databases.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import aero.pilotlog.databases.entities.ZLimit;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table ZLIMIT.
*/
public class ZLimitDao extends AbstractDao<ZLimit, Integer> {

    public static final String TABLENAME = "ZLIMIT";

    /**
     * Properties of entity ZLimit.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property LPeriodCode = new Property(0, Integer.class, "LPeriodCode", true, "LPERIODCODE");
        public final static Property LPeriodLong = new Property(1, String.class, "LPeriodLong", false, "LPERIODLONG");
        public final static Property Record_Modified = new Property(2, Long.class, "Record_Modified", false, "RECORD_MODIFIED");
    };


    public ZLimitDao(DaoConfig config) {
        super(config);
    }
    
    public ZLimitDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'ZLIMIT' (" + //
                "'LPERIODCODE' INTEGER PRIMARY KEY ," + // 0: LPeriodCode
                "'LPERIODLONG' TEXT," + // 1: LPeriodLong
                "'RECORD_MODIFIED' INTEGER);"); // 2: Record_Modified
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'ZLIMIT'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ZLimit entity) {
        stmt.clearBindings();
 
        Integer LPeriodCode = entity.getLPeriodCode();
        if (LPeriodCode != null) {
            stmt.bindLong(1, LPeriodCode);
        }
 
        String LPeriodLong = entity.getLPeriodLong();
        if (LPeriodLong != null) {
            stmt.bindString(2, LPeriodLong);
        }
 
        Long Record_Modified = entity.getRecord_Modified();
        if (Record_Modified != null) {
            stmt.bindLong(3, Record_Modified);
        }
    }

    /** @inheritdoc */
    @Override
    public Integer readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getInt(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public ZLimit readEntity(Cursor cursor, int offset) {
        ZLimit entity = new ZLimit( //
            cursor.isNull(offset + 0) ? null : cursor.getInt(offset + 0), // LPeriodCode
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // LPeriodLong
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2) // Record_Modified
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ZLimit entity, int offset) {
        entity.setLPeriodCode(cursor.isNull(offset + 0) ? null : cursor.getInt(offset + 0));
        entity.setLPeriodLong(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setRecord_Modified(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Integer updateKeyAfterInsert(ZLimit entity, long rowId) {
        return entity.getLPeriodCode();
    }
    
    /** @inheritdoc */
    @Override
    public Integer getKey(ZLimit entity) {
        if(entity != null) {
            return entity.getLPeriodCode();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
