package aero.pilotlog.databases.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table AIRCRAFT.
 */
public class Aircraft {

    private byte[] AircraftCode;
    private Boolean Active;
    private Integer DeviceCode;
    private String Company;
    private String Reference;
    private String RefSearch;
    private String Fin;
    private String Make;
    private String Model;
    private String SubModel;
    private String Rating;
    private Integer Category;
    private Integer Class;
    private Boolean Sea;
    private Integer Power;
    private Boolean Kg5700;
    private Boolean TMG;
    private Boolean Tailwheel;
    private Boolean Complex;
    private Boolean HighPerf;
    private Boolean Aerobatic;
    private Integer Seats;
    private Integer FNPT;
    private Integer DefaultApp;
    private Integer DefaultLaunch;
    private Integer DefaultOps;
    private Integer DefaultLog;
    private Integer CondLog;
    private Boolean Run2;
    private Long Record_Modified;
    private Boolean Record_Upload;
    private boolean mIsSelected = false;

    public Aircraft() {
    }

    public Aircraft(byte[] AircraftCode) {
        this.AircraftCode = AircraftCode;
    }

    public Aircraft(byte[] AircraftCode, Boolean Active, Integer DeviceCode, String Company, String Reference, String RefSearch, String Fin, String Make, String Model, String SubModel, String Rating, Integer Category, Integer Class, Boolean Sea, Integer Power, Boolean Kg5700, Boolean TMG, Boolean Tailwheel, Boolean Complex, Boolean HighPerf, Boolean Aerobatic, Integer Seats, Integer FNPT, Integer DefaultApp, Integer DefaultLaunch, Integer DefaultOps, Integer DefaultLog, Integer CondLog, Boolean Run2, Long Record_Modified, Boolean Record_Upload) {
        this.AircraftCode = AircraftCode;
        this.Active = Active;
        this.DeviceCode = DeviceCode;
        this.Company = Company;
        this.Reference = Reference;
        this.RefSearch = RefSearch;
        this.Fin = Fin;
        this.Make = Make;
        this.Model = Model;
        this.SubModel = SubModel;
        this.Rating = Rating;
        this.Category = Category;
        this.Class = Class;
        this.Sea = Sea;
        this.Power = Power;
        this.Kg5700 = Kg5700;
        this.TMG = TMG;
        this.Tailwheel = Tailwheel;
        this.Complex = Complex;
        this.HighPerf = HighPerf;
        this.Aerobatic = Aerobatic;
        this.Seats = Seats;
        this.FNPT = FNPT;
        this.DefaultApp = DefaultApp;
        this.DefaultLaunch = DefaultLaunch;
        this.DefaultOps = DefaultOps;
        this.DefaultLog = DefaultLog;
        this.CondLog = CondLog;
        this.Run2 = Run2;
        this.Record_Modified = Record_Modified;
        this.Record_Upload = Record_Upload;
        this.mIsSelected = false;

    }

    public byte[] getAircraftCode() {
        return AircraftCode;
    }

    public void setAircraftCode(byte[] AircraftCode) {
        this.AircraftCode = AircraftCode;
    }

    public Boolean getActive() {
        return Active;
    }

    public void setActive(Boolean Active) {
        this.Active = Active;
    }

    public Integer getDeviceCode() {
        return DeviceCode;
    }

    public void setDeviceCode(Integer DeviceCode) {
        this.DeviceCode = DeviceCode;
    }

    public String getCompany() {
        return Company;
    }

    public void setCompany(String Company) {
        this.Company = Company;
    }

    public String getReference() {
        return Reference;
    }

    public void setReference(String Reference) {
        this.Reference = Reference;
    }

    public String getRefSearch() {
        return RefSearch;
    }

    public void setRefSearch(String RefSearch) {
        this.RefSearch = RefSearch;
    }

    public String getFin() {
        return Fin;
    }

    public void setFin(String Fin) {
        this.Fin = Fin;
    }

    public String getMake() {
        return Make;
    }

    public void setMake(String Make) {
        this.Make = Make;
    }

    public String getModel() {
        return Model;
    }

    public void setModel(String Model) {
        this.Model = Model;
    }

    public String getSubModel() {
        return SubModel;
    }

    public void setSubModel(String SubModel) {
        this.SubModel = SubModel;
    }

    public String getRating() {
        return Rating;
    }

    public void setRating(String Rating) {
        this.Rating = Rating;
    }

    public Integer getCategory() {
        return Category;
    }

    public void setCategory(Integer Category) {
        this.Category = Category;
    }

    public Integer getClassZ() {
        return Class;
    }

    public void setClass(Integer Class) {
        this.Class = Class;
    }

    public Boolean getSea() {
        return Sea;
    }

    public void setSea(Boolean Sea) {
        this.Sea = Sea;
    }

    public Integer getPower() {
        return Power;
    }

    public void setPower(Integer Power) {
        this.Power = Power;
    }

    public Boolean getKg5700() {
        return Kg5700;
    }

    public void setKg5700(Boolean Kg5700) {
        this.Kg5700 = Kg5700;
    }

    public Boolean getTMG() {
        return TMG;
    }

    public void setTMG(Boolean TMG) {
        this.TMG = TMG;
    }

    public Boolean getTailwheel() {
        return Tailwheel;
    }

    public void setTailwheel(Boolean Tailwheel) {
        this.Tailwheel = Tailwheel;
    }

    public Boolean getComplex() {
        return Complex;
    }

    public void setComplex(Boolean Complex) {
        this.Complex = Complex;
    }

    public Boolean getHighPerf() {
        return HighPerf;
    }

    public void setHighPerf(Boolean HighPerf) {
        this.HighPerf = HighPerf;
    }

    public Boolean getAerobatic() {
        return Aerobatic;
    }

    public void setAerobatic(Boolean Aerobatic) {
        this.Aerobatic = Aerobatic;
    }

    public Integer getSeats() {
        return Seats;
    }

    public void setSeats(Integer Seats) {
        this.Seats = Seats;
    }

    public Integer getFNPT() {
        return FNPT;
    }

    public void setFNPT(Integer FNPT) {
        this.FNPT = FNPT;
    }

    public Integer getDefaultApp() {
        return DefaultApp;
    }

    public void setDefaultApp(Integer DefaultApp) {
        this.DefaultApp = DefaultApp;
    }

    public Integer getDefaultLaunch() {
        return DefaultLaunch;
    }

    public void setDefaultLaunch(Integer DefaultLaunch) {
        this.DefaultLaunch = DefaultLaunch;
    }

    public Integer getDefaultOps() {
        return DefaultOps;
    }

    public void setDefaultOps(Integer DefaultOps) {
        this.DefaultOps = DefaultOps;
    }

    public Integer getDefaultLog() {
        return DefaultLog;
    }

    public void setDefaultLog(Integer DefaultLog) {
        this.DefaultLog = DefaultLog;
    }

    public Integer getCondLog() {
        return CondLog;
    }

    public void setCondLog(Integer CondLog) {
        this.CondLog = CondLog;
    }

    public Boolean getRun2() {
        return Run2;
    }

    public void setRun2(Boolean Run2) {
        this.Run2 = Run2;
    }

    public Long getRecord_Modified() {
        return Record_Modified;
    }

    public void setRecord_Modified(Long Record_Modified) {
        this.Record_Modified = Record_Modified;
    }

    public Boolean getRecord_Upload() {
        return Record_Upload;
    }

    public void setRecord_Upload(Boolean Record_Upload) {
        this.Record_Upload = Record_Upload;
    }

    public boolean isSelected() {
        return mIsSelected;
    }

    public void setSelected(boolean mIsSelected) {
        this.mIsSelected = mIsSelected;
    }
}
