package aero.pilotlog.databases.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table AIRFIELD.
 */
public class Airfield {

    private byte[] AFCode;
    private String AFICAO;
    private String AFIATA;
    private String AFFAA;
    private String AFName;
    private Integer Latitude;
    private Integer Longitude;
    private Integer AFCountry;
    private Integer AFCat;
    private Integer ElevationFT;
    private Integer TZCode;
    private String City;
    private String Notes;
    private String NotesUser;
    private Boolean ShowList;
    private Boolean UserEdit;
    private Long Record_Modified;
    private Boolean Record_Upload;
    private boolean IsSelected = false;

    public Airfield() {
    }

    public Airfield(byte[] AFCode) {
        this.AFCode = AFCode;
    }

    public Airfield(byte[] AFCode, String AFICAO, String AFIATA, String AFFAA, String AFName, Integer Latitude, Integer Longitude, Integer AFCountry, Integer AFCat, Integer ElevationFT, Integer TZCode, String City, String Notes, String NotesUser, Boolean ShowList, Boolean UserEdit, Long Record_Modified, Boolean Record_Upload) {
        this.AFCode = AFCode;
        this.AFICAO = AFICAO;
        this.AFIATA = AFIATA;
        this.AFFAA = AFFAA;
        this.AFName = AFName;
        this.Latitude = Latitude;
        this.Longitude = Longitude;
        this.AFCountry = AFCountry;
        this.AFCat = AFCat;
        this.ElevationFT = ElevationFT;
        this.TZCode = TZCode;
        this.City = City;
        this.Notes = Notes;
        this.NotesUser = NotesUser;
        this.ShowList = ShowList;
        this.UserEdit = UserEdit;
        this.Record_Modified = Record_Modified;
        this.Record_Upload = Record_Upload;
        this.IsSelected = false;
    }

    public byte[] getAFCode() {
        return AFCode;
    }

    public void setAFCode(byte[] AFCode) {
        this.AFCode = AFCode;
    }

    public String getAFICAO() {
        return AFICAO;
    }

    public void setAFICAO(String AFICAO) {
        this.AFICAO = AFICAO;
    }

    public String getAFIATA() {
        return AFIATA;
    }

    public void setAFIATA(String AFIATA) {
        this.AFIATA = AFIATA;
    }

    public String getAFFAA() {
        return AFFAA;
    }

    public void setAFFAA(String AFFAA) {
        this.AFFAA = AFFAA;
    }

    public String getAFName() {
        return AFName;
    }

    public void setAFName(String AFName) {
        this.AFName = AFName;
    }

    public Integer getLatitude() {
        return Latitude;
    }

    public void setLatitude(Integer Latitude) {
        this.Latitude = Latitude;
    }

    public Integer getLongitude() {
        return Longitude;
    }

    public void setLongitude(Integer Longitude) {
        this.Longitude = Longitude;
    }

    public Integer getAFCountry() {
        return AFCountry;
    }

    public void setAFCountry(Integer AFCountry) {
        this.AFCountry = AFCountry;
    }

    public Integer getAFCat() {
        return AFCat;
    }

    public void setAFCat(Integer AFCat) {
        this.AFCat = AFCat;
    }

    public Integer getElevationFT() {
        return ElevationFT;
    }

    public void setElevationFT(Integer ElevationFT) {
        this.ElevationFT = ElevationFT;
    }

    public Integer getTZCode() {
        return TZCode;
    }

    public void setTZCode(Integer TZCode) {
        this.TZCode = TZCode;
    }

    public String getCity() {
        return City;
    }

    public void setCity(String City) {
        this.City = City;
    }

    public String getNotes() {
        return Notes;
    }

    public void setNotes(String Notes) {
        this.Notes = Notes;
    }

    public String getNotesUser() {
        return NotesUser;
    }

    public void setNotesUser(String NotesUser) {
        this.NotesUser = NotesUser;
    }

    public Boolean getShowList() {
        return ShowList;
    }

    public void setShowList(Boolean ShowList) {
        this.ShowList = ShowList;
    }

    public Boolean getUserEdit() {
        return UserEdit;
    }

    public void setUserEdit(Boolean UserEdit) {
        this.UserEdit = UserEdit;
    }

    public Long getRecord_Modified() {
        return Record_Modified;
    }

    public void setRecord_Modified(Long Record_Modified) {
        this.Record_Modified = Record_Modified;
    }

    public Boolean getRecord_Upload() {
        return Record_Upload;
    }

    public void setRecord_Upload(Boolean Record_Upload) {
        this.Record_Upload = Record_Upload;
    }

    public boolean isSelected() {
        return IsSelected;
    }

    public void setSelected(boolean selected) {
        IsSelected = selected;
    }

}
