package aero.pilotlog.databases.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ALLOWANCE_RULES.
 */
public class AllowanceRules {

    private byte[] ARCode;
    private Integer ARType;
    private Integer ARClassEngine;
    private String ARModel;
    private String ARSubModel;
    private Integer ARCurrency;
    private Integer ARCostFix;
    private Integer ARCostVar;
    private Integer ARCostMinHour;
    private Integer ARCostBase;
    private Integer ARWhen;
    private String ARWhen1;
    private String ARWhen2;
    private String ARReadable;
    private Long Record_Modified;
    private Boolean Record_Upload;

    public AllowanceRules() {
    }

    public AllowanceRules(byte[] ARCode) {
        this.ARCode = ARCode;
    }

    public AllowanceRules(byte[] ARCode, Integer ARType, Integer ARClassEngine, String ARModel, String ARSubModel, Integer ARCurrency, Integer ARCostFix, Integer ARCostVar, Integer ARCostMinHour, Integer ARCostBase, Integer ARWhen, String ARWhen1, String ARWhen2, String ARReadable, Long Record_Modified, Boolean Record_Upload) {
        this.ARCode = ARCode;
        this.ARType = ARType;
        this.ARClassEngine = ARClassEngine;
        this.ARModel = ARModel;
        this.ARSubModel = ARSubModel;
        this.ARCurrency = ARCurrency;
        this.ARCostFix = ARCostFix;
        this.ARCostVar = ARCostVar;
        this.ARCostMinHour = ARCostMinHour;
        this.ARCostBase = ARCostBase;
        this.ARWhen = ARWhen;
        this.ARWhen1 = ARWhen1;
        this.ARWhen2 = ARWhen2;
        this.ARReadable = ARReadable;
        this.Record_Modified = Record_Modified;
        this.Record_Upload = Record_Upload;
    }

    public byte[] getARCode() {
        return ARCode;
    }

    public void setARCode(byte[] ARCode) {
        this.ARCode = ARCode;
    }

    public Integer getARType() {
        return ARType;
    }

    public void setARType(Integer ARType) {
        this.ARType = ARType;
    }

    public Integer getARClassEngine() {
        return ARClassEngine;
    }

    public void setARClassEngine(Integer ARClassEngine) {
        this.ARClassEngine = ARClassEngine;
    }

    public String getARModel() {
        return ARModel;
    }

    public void setARModel(String ARModel) {
        this.ARModel = ARModel;
    }

    public String getARSubModel() {
        return ARSubModel;
    }

    public void setARSubModel(String ARSubModel) {
        this.ARSubModel = ARSubModel;
    }

    public Integer getARCurrency() {
        return ARCurrency;
    }

    public void setARCurrency(Integer ARCurrency) {
        this.ARCurrency = ARCurrency;
    }

    public Integer getARCostFix() {
        return ARCostFix;
    }

    public void setARCostFix(Integer ARCostFix) {
        this.ARCostFix = ARCostFix;
    }

    public Integer getARCostVar() {
        return ARCostVar;
    }

    public void setARCostVar(Integer ARCostVar) {
        this.ARCostVar = ARCostVar;
    }

    public Integer getARCostMinHour() {
        return ARCostMinHour;
    }

    public void setARCostMinHour(Integer ARCostMinHour) {
        this.ARCostMinHour = ARCostMinHour;
    }

    public Integer getARCostBase() {
        return ARCostBase;
    }

    public void setARCostBase(Integer ARCostBase) {
        this.ARCostBase = ARCostBase;
    }

    public Integer getARWhen() {
        return ARWhen;
    }

    public void setARWhen(Integer ARWhen) {
        this.ARWhen = ARWhen;
    }

    public String getARWhen1() {
        return ARWhen1;
    }

    public void setARWhen1(String ARWhen1) {
        this.ARWhen1 = ARWhen1;
    }

    public String getARWhen2() {
        return ARWhen2;
    }

    public void setARWhen2(String ARWhen2) {
        this.ARWhen2 = ARWhen2;
    }

    public String getARReadable() {
        return ARReadable;
    }

    public void setARReadable(String ARReadable) {
        this.ARReadable = ARReadable;
    }

    public Long getRecord_Modified() {
        return Record_Modified;
    }

    public void setRecord_Modified(Long Record_Modified) {
        this.Record_Modified = Record_Modified;
    }

    public Boolean getRecord_Upload() {
        return Record_Upload;
    }

    public void setRecord_Upload(Boolean Record_Upload) {
        this.Record_Upload = Record_Upload;
    }

}
