package aero.pilotlog.databases.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BACKUP_DB.
 */
public class BackupDB {

    private byte[] BackupCode;
    private String DateTime;
    private Integer FlightRecords;
    private String dbURL;
    private Long Record_Modified;
    private Boolean Record_Upload;

    public BackupDB() {
    }

    public BackupDB(byte[] BackupCode) {
        this.BackupCode = BackupCode;
    }

    public BackupDB(byte[] BackupCode, String DateTime, Integer FlightRecords, String dbURL, Long Record_Modified, Boolean Record_Upload) {
        this.BackupCode = BackupCode;
        this.DateTime = DateTime;
        this.FlightRecords = FlightRecords;
        this.dbURL = dbURL;
        this.Record_Modified = Record_Modified;
        this.Record_Upload = Record_Upload;
    }

    public byte[] getBackupCode() {
        return BackupCode;
    }

    public void setBackupCode(byte[] BackupCode) {
        this.BackupCode = BackupCode;
    }

    public String getDateTime() {
        return DateTime;
    }

    public void setDateTime(String DateTime) {
        this.DateTime = DateTime;
    }

    public Integer getFlightRecords() {
        return FlightRecords;
    }

    public void setFlightRecords(Integer FlightRecords) {
        this.FlightRecords = FlightRecords;
    }

    public String getDbURL() {
        return dbURL;
    }

    public void setDbURL(String dbURL) {
        this.dbURL = dbURL;
    }

    public Long getRecord_Modified() {
        return Record_Modified;
    }

    public void setRecord_Modified(Long Record_Modified) {
        this.Record_Modified = Record_Modified;
    }

    public Boolean getRecord_Upload() {
        return Record_Upload;
    }

    public void setRecord_Upload(Boolean Record_Upload) {
        this.Record_Upload = Record_Upload;
    }

}
