package aero.pilotlog.databases.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DUTY.
 */
public class Duty {

    private byte[] DutyCode;
    private Integer DutyType;
    private Boolean Deadhead;
    private String EventDescription;
    private String EventDateUTC;
    private String EventDateLOCAL;
    private String EventDateBASE;
    private Integer EventStartUTC;
    private Integer EventEndUTC;
    private Integer StartOffset;
    private Integer EndOffset;
    private Integer BaseOffset;
    private Integer StartTZCode;
    private Integer EndTZCode;
    private Integer Duration;
    private String DutyNotes;
    private Long Record_Modified;
    private Boolean Record_Upload;

    public Duty() {
    }

    public Duty(byte[] DutyCode) {
        this.DutyCode = DutyCode;
    }

    public Duty(byte[] DutyCode, Integer DutyType, Boolean Deadhead, String EventDescription, String EventDateUTC, String EventDateLOCAL, String EventDateBASE, Integer EventStartUTC, Integer EventEndUTC, Integer StartOffset, Integer EndOffset, Integer BaseOffset, Integer StartTZCode, Integer EndTZCode, Integer Duration, String DutyNotes, Long Record_Modified, Boolean Record_Upload) {
        this.DutyCode = DutyCode;
        this.DutyType = DutyType;
        this.Deadhead = Deadhead;
        this.EventDescription = EventDescription;
        this.EventDateUTC = EventDateUTC;
        this.EventDateLOCAL = EventDateLOCAL;
        this.EventDateBASE = EventDateBASE;
        this.EventStartUTC = EventStartUTC;
        this.EventEndUTC = EventEndUTC;
        this.StartOffset = StartOffset;
        this.EndOffset = EndOffset;
        this.BaseOffset = BaseOffset;
        this.StartTZCode = StartTZCode;
        this.EndTZCode = EndTZCode;
        this.Duration = Duration;
        this.DutyNotes = DutyNotes;
        this.Record_Modified = Record_Modified;
        this.Record_Upload = Record_Upload;
    }

    public byte[] getDutyCode() {
        return DutyCode;
    }

    public void setDutyCode(byte[] DutyCode) {
        this.DutyCode = DutyCode;
    }

    public Integer getDutyType() {
        return DutyType;
    }

    public void setDutyType(Integer DutyType) {
        this.DutyType = DutyType;
    }

    public Boolean getDeadhead() {
        return Deadhead;
    }

    public void setDeadhead(Boolean Deadhead) {
        this.Deadhead = Deadhead;
    }

    public String getEventDescription() {
        return EventDescription;
    }

    public void setEventDescription(String EventDescription) {
        this.EventDescription = EventDescription;
    }

    public String getEventDateUTC() {
        return EventDateUTC;
    }

    public void setEventDateUTC(String EventDateUTC) {
        this.EventDateUTC = EventDateUTC;
    }

    public String getEventDateLOCAL() {
        return EventDateLOCAL;
    }

    public void setEventDateLOCAL(String EventDateLOCAL) {
        this.EventDateLOCAL = EventDateLOCAL;
    }

    public String getEventDateBASE() {
        return EventDateBASE;
    }

    public void setEventDateBASE(String EventDateBASE) {
        this.EventDateBASE = EventDateBASE;
    }

    public Integer getEventStartUTC() {
        return EventStartUTC;
    }

    public void setEventStartUTC(Integer EventStartUTC) {
        this.EventStartUTC = EventStartUTC;
    }

    public Integer getEventEndUTC() {
        return EventEndUTC;
    }

    public void setEventEndUTC(Integer EventEndUTC) {
        this.EventEndUTC = EventEndUTC;
    }

    public Integer getStartOffset() {
        return StartOffset;
    }

    public void setStartOffset(Integer StartOffset) {
        this.StartOffset = StartOffset;
    }

    public Integer getEndOffset() {
        return EndOffset;
    }

    public void setEndOffset(Integer EndOffset) {
        this.EndOffset = EndOffset;
    }

    public Integer getBaseOffset() {
        return BaseOffset;
    }

    public void setBaseOffset(Integer BaseOffset) {
        this.BaseOffset = BaseOffset;
    }

    public Integer getStartTZCode() {
        return StartTZCode;
    }

    public void setStartTZCode(Integer StartTZCode) {
        this.StartTZCode = StartTZCode;
    }

    public Integer getEndTZCode() {
        return EndTZCode;
    }

    public void setEndTZCode(Integer EndTZCode) {
        this.EndTZCode = EndTZCode;
    }

    public Integer getDuration() {
        return Duration;
    }

    public void setDuration(Integer Duration) {
        this.Duration = Duration;
    }

    public String getDutyNotes() {
        return DutyNotes;
    }

    public void setDutyNotes(String DutyNotes) {
        this.DutyNotes = DutyNotes;
    }

    public Long getRecord_Modified() {
        return Record_Modified;
    }

    public void setRecord_Modified(Long Record_Modified) {
        this.Record_Modified = Record_Modified;
    }

    public Boolean getRecord_Upload() {
        return Record_Upload;
    }

    public void setRecord_Upload(Boolean Record_Upload) {
        this.Record_Upload = Record_Upload;
    }

}
