package aero.pilotlog.databases.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table EXPENSE.
 */
public class Expense {

    private byte[] ExpCode;
    private String ExpDate;
    private Integer ETCode;
    private String Description;
    private Long Amount;
    private Integer CurrCode;
    private Long AmountForeign;
    private Integer CurrCodeForeign;
    private Integer LinkTable;
    private byte[] LinkCode;
    private Long Record_Modified;
    private Boolean Record_Upload;

    public Expense() {
    }

    public Expense(byte[] ExpCode) {
        this.ExpCode = ExpCode;
    }

    public Expense(byte[] ExpCode, String ExpDate, Integer ETCode, String Description, Long Amount, Integer CurrCode, Long AmountForeign, Integer CurrCodeForeign, Integer LinkTable, byte[] LinkCode, Long Record_Modified, Boolean Record_Upload) {
        this.ExpCode = ExpCode;
        this.ExpDate = ExpDate;
        this.ETCode = ETCode;
        this.Description = Description;
        this.Amount = Amount;
        this.CurrCode = CurrCode;
        this.AmountForeign = AmountForeign;
        this.CurrCodeForeign = CurrCodeForeign;
        this.LinkTable = LinkTable;
        this.LinkCode = LinkCode;
        this.Record_Modified = Record_Modified;
        this.Record_Upload = Record_Upload;
    }

    public byte[] getExpCode() {
        return ExpCode;
    }

    public void setExpCode(byte[] ExpCode) {
        this.ExpCode = ExpCode;
    }

    public String getExpDate() {
        return ExpDate;
    }

    public void setExpDate(String ExpDate) {
        this.ExpDate = ExpDate;
    }

    public Integer getETCode() {
        return ETCode;
    }

    public void setETCode(Integer ETCode) {
        this.ETCode = ETCode;
    }

    public String getDescription() {
        return Description;
    }

    public void setDescription(String Description) {
        this.Description = Description;
    }

    public Long getAmount() {
        return Amount;
    }

    public void setAmount(Long Amount) {
        this.Amount = Amount;
    }

    public Integer getCurrCode() {
        return CurrCode;
    }

    public void setCurrCode(Integer CurrCode) {
        this.CurrCode = CurrCode;
    }

    public Long getAmountForeign() {
        return AmountForeign;
    }

    public void setAmountForeign(Long AmountForeign) {
        this.AmountForeign = AmountForeign;
    }

    public Integer getCurrCodeForeign() {
        return CurrCodeForeign;
    }

    public void setCurrCodeForeign(Integer CurrCodeForeign) {
        this.CurrCodeForeign = CurrCodeForeign;
    }

    public Integer getLinkTable() {
        return LinkTable;
    }

    public void setLinkTable(Integer LinkTable) {
        this.LinkTable = LinkTable;
    }

    public byte[] getLinkCode() {
        return LinkCode;
    }

    public void setLinkCode(byte[] LinkCode) {
        this.LinkCode = LinkCode;
    }

    public Long getRecord_Modified() {
        return Record_Modified;
    }

    public void setRecord_Modified(Long Record_Modified) {
        this.Record_Modified = Record_Modified;
    }

    public Boolean getRecord_Upload() {
        return Record_Upload;
    }

    public void setRecord_Upload(Boolean Record_Upload) {
        this.Record_Upload = Record_Upload;
    }

}
