package aero.pilotlog.databases.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table FLIGHT.
 */
public class Flight {

    private byte[] FlightCode;
    private String DateUTC;
    private String DateLOCAL;
    private String DateBASE;
    private String FlightNumber;
    private String Pairing;
    private byte[] AircraftCode;
    private byte[] DepCode;
    private byte[] ArrCode;
    private String DepRwy;
    private String ArrRwy;
    private Integer DepTimeUTC;
    private Integer ArrTimeUTC;
    private Integer DepTimeSCHED;
    private Integer ArrTimeSCHED;
    private Integer ToTimeUTC;
    private Integer LdgTimeUTC;
    private Integer DepOffset;
    private Integer ArrOffset;
    private Integer BaseOffset;
    private Integer minTOTAL;
    private Integer minAIR;
    private Integer minPIC;
    private Integer minPICUS;
    private Integer minCOP;
    private Integer minDUAL;
    private Integer minINSTR;
    private Integer minEXAM;
    private Integer minREL;
    private Integer minNIGHT;
    private Integer minXC;
    private Integer minIFR;
    private Integer minIMT;
    private Integer minSFR;
    private Integer minU1;
    private Integer minU2;
    private Integer minU3;
    private Integer minU4;
    private Long hobbsOut;
    private Long hobbsIn;
    private Integer ToDay;
    private Integer ToNight;
    private Integer LdgDay;
    private Integer LdgNight;
    private Integer Holding;
    private Integer LiftSW;
    private Integer Fuel;
    private Integer FuelUsed;
    private Integer FuelPlanned;
    private Integer Pax;
    private Boolean DeIce;
    private Integer UserNum;
    private String UserText;
    private Boolean UserBool;
    private String TagApproach;
    private String TagLaunch;
    private String TagOps;
    private String TagDelay;
    private Boolean PF;
    private byte[] P1Code;
    private byte[] P2Code;
    private byte[] P3Code;
    private byte[] P4Code;
    private String CrewList;
    private String Training;
    private String Remarks;
    private String Report;
    private Integer SignBox;
    private Boolean NextPage;
    private Boolean NextSummary;
    private Boolean ToEdit;
    private Long Record_Modified;
    private Boolean Record_Upload;

    public Flight() {
    }

    public Flight(byte[] FlightCode) {
        this.FlightCode = FlightCode;
    }

    public Flight(byte[] FlightCode, String DateUTC, String DateLOCAL, String DateBASE, String FlightNumber, String Pairing,
                  byte[] AircraftCode, byte[] DepCode, byte[] ArrCode, String DepRwy, String ArrRwy,
                  Integer DepTimeUTC, Integer ArrTimeUTC, Integer DepTimeSCHED, Integer ArrTimeSCHED, Integer ToTimeUTC,
                  Integer LdgTimeUTC, Integer DepOffset, Integer ArrOffset, Integer BaseOffset, Integer minTOTAL, Integer minAIR,
                  Integer minPIC, Integer minPICUS, Integer minCOP, Integer minDUAL, Integer minINSTR, Integer minEXAM,
                  Integer minREL, Integer minNIGHT, Integer minXC, Integer minIFR, Integer minIMT, Integer minSFR,
                  Integer minU1, Integer minU2, Integer minU3, Integer minU4, Long hobbsOut, Long hobbsIn, Integer ToDay, Integer ToNight, Integer LdgDay,
                  Integer LdgNight, Integer Holding, Integer LiftSW, Integer Fuel, Integer FuelUsed, Integer FuelPlanned,
                  Integer Pax, Boolean DeIce, Integer UserNum, String UserText, Boolean UserBool, String TagApproach,
                  String TagLaunch, String TagOps, String TagDelay, Boolean PF, byte[] P1Code, byte[] P2Code, byte[] P3Code,
                  byte[] P4Code, String CrewList, String Training, String Remarks, String Report, Integer SignBox,
                  Boolean NextPage, Boolean NextSummary, Boolean ToEdit, Long Record_Modified, Boolean Record_Upload) {
        this.FlightCode = FlightCode;
        this.DateUTC = DateUTC;
        this.DateLOCAL = DateLOCAL;
        this.DateBASE = DateBASE;
        this.FlightNumber = FlightNumber;
        this.Pairing = Pairing;
        this.AircraftCode = AircraftCode;
        this.DepCode = DepCode;
        this.ArrCode = ArrCode;
        this.DepRwy = DepRwy;
        this.ArrRwy = ArrRwy;
        this.DepTimeUTC = DepTimeUTC;
        this.ArrTimeUTC = ArrTimeUTC;
        this.DepTimeSCHED = DepTimeSCHED;
        this.ArrTimeSCHED = ArrTimeSCHED;
        this.ToTimeUTC = ToTimeUTC;
        this.LdgTimeUTC = LdgTimeUTC;
        this.DepOffset = DepOffset;
        this.ArrOffset = ArrOffset;
        this.BaseOffset = BaseOffset;
        this.minTOTAL = minTOTAL;
        this.minAIR = minAIR;
        this.minPIC = minPIC;
        this.minPICUS = minPICUS;
        this.minCOP = minCOP;
        this.minDUAL = minDUAL;
        this.minINSTR = minINSTR;
        this.minEXAM = minEXAM;
        this.minREL = minREL;
        this.minNIGHT = minNIGHT;
        this.minXC = minXC;
        this.minIFR = minIFR;
        this.minIMT = minIMT;
        this.minSFR = minSFR;
        this.minU1 = minU1;
        this.minU2 = minU2;
        this.minU3 = minU3;
        this.minU4 = minU4;
        this.hobbsOut = hobbsOut;
        this.hobbsIn = hobbsIn;
        this.ToDay = ToDay;
        this.ToNight = ToNight;
        this.LdgDay = LdgDay;
        this.LdgNight = LdgNight;
        this.Holding = Holding;
        this.LiftSW = LiftSW;
        this.Fuel = Fuel;
        this.FuelUsed = FuelUsed;
        this.FuelPlanned = FuelPlanned;
        this.Pax = Pax;
        this.DeIce = DeIce;
        this.UserNum = UserNum;
        this.UserText = UserText;
        this.UserBool = UserBool;
        this.TagApproach = TagApproach;
        this.TagLaunch = TagLaunch;
        this.TagOps = TagOps;
        this.TagDelay = TagDelay;
        this.PF = PF;
        this.P1Code = P1Code;
        this.P2Code = P2Code;
        this.P3Code = P3Code;
        this.P4Code = P4Code;
        this.CrewList = CrewList;
        this.Training = Training;
        this.Remarks = Remarks;
        this.Report = Report;
        this.SignBox = SignBox;
        this.NextPage = NextPage;
        this.NextSummary = NextSummary;
        this.ToEdit = ToEdit;
        this.Record_Modified = Record_Modified;
        this.Record_Upload = Record_Upload;
    }

    public byte[] getFlightCode() {
        return FlightCode;
    }

    public void setFlightCode(byte[] FlightCode) {
        this.FlightCode = FlightCode;
    }

    public String getDateUTC() {
        return DateUTC;
    }

    public void setDateUTC(String DateUTC) {
        this.DateUTC = DateUTC;
    }

    public String getDateLOCAL() {
        return DateLOCAL;
    }

    public void setDateLOCAL(String DateLOCAL) {
        this.DateLOCAL = DateLOCAL;
    }

    public String getDateBASE() {
        return DateBASE;
    }

    public void setDateBASE(String DateBASE) {
        this.DateBASE = DateBASE;
    }

    public String getFlightNumber() {
        return FlightNumber != null ? FlightNumber : "";
    }

    public void setFlightNumber(String FlightNumber) {
        this.FlightNumber = FlightNumber;
    }

    public String getPairing() {
        return Pairing != null ? Pairing : "";
    }

    public void setPairing(String Pairing) {
        this.Pairing = Pairing;
    }

    public byte[] getAircraftCode() {
        return AircraftCode;
    }

    public void setAircraftCode(byte[] AircraftCode) {
        this.AircraftCode = AircraftCode;
    }

    public byte[] getDepCode() {
        return DepCode;
    }

    public void setDepCode(byte[] DepCode) {
        this.DepCode = DepCode;
    }

    public byte[] getArrCode() {
        return ArrCode;
    }

    public void setArrCode(byte[] ArrCode) {
        this.ArrCode = ArrCode;
    }

    public String getDepRwy() {
        return DepRwy != null ? DepRwy : "";
    }

    public void setDepRwy(String DepRwy) {
        this.DepRwy = DepRwy;
    }

    public String getArrRwy() {
        return ArrRwy != null ? ArrRwy : "";
    }

    public void setArrRwy(String ArrRwy) {
        this.ArrRwy = ArrRwy;
    }

    public Integer getDepTimeUTC() {
        return DepTimeUTC != null ? DepTimeUTC : 0;
    }

    public void setDepTimeUTC(Integer DepTimeUTC) {
        this.DepTimeUTC = DepTimeUTC;
    }

    public Integer getArrTimeUTC() {
        return ArrTimeUTC != null ? ArrTimeUTC : 0;
    }

    public void setArrTimeUTC(Integer ArrTimeUTC) {
        this.ArrTimeUTC = ArrTimeUTC;
    }

    public Integer getDepTimeSCHED() {
        return DepTimeSCHED != null ? DepTimeSCHED : 0;
    }

    public void setDepTimeSCHED(Integer DepTimeSCHED) {
        this.DepTimeSCHED = DepTimeSCHED;
    }

    public Integer getArrTimeSCHED() {
        return ArrTimeSCHED != null ? ArrTimeSCHED : 0;
    }

    public void setArrTimeSCHED(Integer ArrTimeSCHED) {
        this.ArrTimeSCHED = ArrTimeSCHED;
    }

    public Integer getToTimeUTC() {
        return ToTimeUTC != null ? ToTimeUTC : 0;
    }

    public void setToTimeUTC(Integer ToTimeUTC) {
        this.ToTimeUTC = ToTimeUTC;
    }

    public Integer getLdgTimeUTC() {
        return LdgTimeUTC != null ? LdgTimeUTC : 0;
    }

    public void setLdgTimeUTC(Integer LdgTimeUTC) {
        this.LdgTimeUTC = LdgTimeUTC;
    }

    public Integer getDepOffset() {
        return DepOffset != null ? DepOffset : 0;
    }

    public void setDepOffset(Integer DepOffset) {
        this.DepOffset = DepOffset;
    }

    public Integer getArrOffset() {
        return ArrOffset != null ? ArrOffset : 0;
    }

    public void setArrOffset(Integer ArrOffset) {
        this.ArrOffset = ArrOffset;
    }

    public Integer getBaseOffset() {
        return BaseOffset != null ? BaseOffset : 0;
    }

    public void setBaseOffset(Integer BaseOffset) {
        this.BaseOffset = BaseOffset;
    }

    public Integer getMinTOTAL() {
        return minTOTAL != null ? minTOTAL : 0;
    }

    public void setMinTOTAL(Integer minTOTAL) {
        this.minTOTAL = minTOTAL;
    }

    public Integer getMinAIR() {
        return minAIR != null ? minAIR : 0;
    }

    public void setMinAIR(Integer minAIR) {
        this.minAIR = minAIR;
    }

    public Integer getMinPIC() {
        return minPIC != null ? minPIC : 0;
    }

    public void setMinPIC(Integer minPIC) {
        this.minPIC = minPIC;
    }

    public Integer getMinPICUS() {
        return minPICUS != null ? minPICUS : 0;
    }

    public void setMinPICUS(Integer minPICUS) {
        this.minPICUS = minPICUS;
    }

    public Integer getMinCOP() {
        return minCOP != null ? minCOP : 0;
    }

    public void setMinCOP(Integer minCOP) {
        this.minCOP = minCOP;
    }

    public Integer getMinDUAL() {
        return minDUAL != null ? minDUAL : 0;
    }

    public void setMinDUAL(Integer minDUAL) {
        this.minDUAL = minDUAL;
    }

    public Integer getMinINSTR() {
        return minINSTR != null ? minINSTR : 0;
    }

    public void setMinINSTR(Integer minINSTR) {
        this.minINSTR = minINSTR;
    }

    public Integer getMinEXAM() {
        return minEXAM != null ? minEXAM : 0;
    }

    public void setMinEXAM(Integer minEXAM) {
        this.minEXAM = minEXAM;
    }

    public Integer getMinREL() {
        return minREL != null ? minREL : 0;
    }

    public void setMinREL(Integer minREL) {
        this.minREL = minREL;
    }

    public Integer getMinNIGHT() {
        return minNIGHT != null ? minNIGHT : 0;
    }

    public void setMinNIGHT(Integer minNIGHT) {
        this.minNIGHT = minNIGHT;
    }

    public Integer getMinXC() {
        return minXC != null ? minXC : 0;
    }

    public void setMinXC(Integer minXC) {
        this.minXC = minXC;
    }

    public Integer getMinIFR() {
        return minIFR != null ? minIFR : 0;
    }

    public void setMinIFR(Integer minIFR) {
        this.minIFR = minIFR;
    }

    public Integer getMinIMT() {
        return minIMT != null ? minIMT : 0;
    }

    public void setMinIMT(Integer minIMT) {
        this.minIMT = minIMT;
    }

    public Integer getMinSFR() {
        return minSFR != null ? minSFR : 0;
    }

    public void setMinSFR(Integer minSFR) {
        this.minSFR = minSFR;
    }

    public Integer getMinU1() {
        return minU1 != null ? minU1 : 0;
    }

    public void setMinU1(Integer minU1) {
        this.minU1 = minU1;
    }

    public Integer getMinU2() {
        return minU2 != null ? minU2 : 0;
    }

    public void setMinU2(Integer minU2) {
        this.minU2 = minU2;
    }

    public Integer getMinU3() {
        return minU3 != null ? minU3 : 0;
    }

    public void setMinU3(Integer minU3) {
        this.minU3 = minU3;
    }

    public Integer getMinU4() {
        return minU4 != null ? minU4 : 0;
    }

    public void setMinU4(Integer minU4) {
        this.minU4 = minU4;
    }

    public Long getHobbsOut() {
        return hobbsOut;
    }

    public void setHobbsOut(Long hobbsOut) {
        this.hobbsOut = hobbsOut;
    }

    public Long getHobbsIn() {
        return hobbsIn;
    }

    public void setHobbsIn(Long hobbsIn) {
        this.hobbsIn = hobbsIn;
    }

    public Integer getToDay() {
        return ToDay != null ? ToDay : 0;
    }

    public void setToDay(Integer ToDay) {
        this.ToDay = ToDay;
    }

    public Integer getToNight() {
        return ToNight != null ? ToNight : 0;
    }

    public void setToNight(Integer ToNight) {
        this.ToNight = ToNight;
    }

    public Integer getLdgDay() {
        return LdgDay != null ? LdgDay : 0;
    }

    public void setLdgDay(Integer LdgDay) {
        this.LdgDay = LdgDay;
    }

    public Integer getLdgNight() {
        return LdgNight != null ? LdgNight : 0;
    }

    public void setLdgNight(Integer LdgNight) {
        this.LdgNight = LdgNight;
    }

    public Integer getHolding() {
        return Holding != null ? Holding : 0;
    }

    public void setHolding(Integer Holding) {
        this.Holding = Holding;
    }

    public Integer getLiftSW() {
        return LiftSW != null ? LiftSW : 0;
    }

    public void setLiftSW(Integer LiftSW) {
        this.LiftSW = LiftSW;
    }

    public Integer getFuel() {
        return Fuel != null ? Fuel : 0;
    }

    public void setFuel(Integer Fuel) {
        this.Fuel = Fuel;
    }

    public Integer getFuelUsed() {
        return FuelUsed != null ? FuelUsed : 0;
    }

    public void setFuelUsed(Integer FuelUsed) {
        this.FuelUsed = FuelUsed;
    }

    public Integer getFuelPlanned() {
        return FuelPlanned != null ? FuelPlanned : 0;
    }

    public void setFuelPlanned(Integer FuelPlanned) {
        this.FuelPlanned = FuelPlanned;
    }

    public Integer getPax() {
        return Pax != null ? Pax : 0;
    }

    public void setPax(Integer Pax) {
        this.Pax = Pax;
    }

    public Boolean getDeIce() {
        return DeIce != null ? DeIce : false;
    }

    public void setDeIce(Boolean DeIce) {
        this.DeIce = DeIce;
    }

    public Integer getUserNum() {
        return UserNum != null ? UserNum : 0;
    }

    public void setUserNum(Integer UserNum) {
        this.UserNum = UserNum;
    }

    public String getUserText() {
        return UserText != null ? UserText : "";
    }

    public void setUserText(String UserText) {
        this.UserText = UserText;
    }

    public Boolean getUserBool() {
        return UserBool != null ? UserBool : false;
    }

    public void setUserBool(Boolean UserBool) {
        this.UserBool = UserBool;
    }

    public String getTagApproach() {
        return TagApproach != null ? TagApproach : "";
    }

    public void setTagApproach(String TagApproach) {
        this.TagApproach = TagApproach;
    }

    public String getTagLaunch() {
        return TagLaunch != null ? TagLaunch : "";
    }

    public void setTagLaunch(String TagLaunch) {
        this.TagLaunch = TagLaunch;
    }

    public String getTagOps() {
        return TagOps != null ? TagOps : "";
    }

    public void setTagOps(String TagOps) {
        this.TagOps = TagOps;
    }

    public String getTagDelay() {
        return TagDelay != null ? TagDelay : "";
    }

    public void setTagDelay(String TagDelay) {
        this.TagDelay = TagDelay;
    }

    public Boolean getPF() {
        return PF != null ? PF : false;
    }

    public void setPF(Boolean PF) {
        this.PF = PF;
    }

    public byte[] getP1Code() {
        return P1Code;
    }

    public void setP1Code(byte[] P1Code) {
        this.P1Code = P1Code;
    }

    public byte[] getP2Code() {
        return P2Code;
    }

    public void setP2Code(byte[] P2Code) {
        this.P2Code = P2Code;
    }

    public byte[] getP3Code() {
        return P3Code;
    }

    public void setP3Code(byte[] P3Code) {
        this.P3Code = P3Code;
    }

    public byte[] getP4Code() {
        return P4Code;
    }

    public void setP4Code(byte[] P4Code) {
        this.P4Code = P4Code;
    }

    public String getCrewList() {
        return CrewList != null ? CrewList : "";
    }

    public void setCrewList(String CrewList) {
        this.CrewList = CrewList;
    }

    public String getTraining() {
        return Training != null ? Training : "";
    }

    public void setTraining(String Training) {
        this.Training = Training;
    }

    public String getRemarks() {
        return Remarks != null ? Remarks : "";
    }

    public void setRemarks(String Remarks) {
        this.Remarks = Remarks;
    }

    public String getReport() {
        return Report != null ? Report : "";
    }

    public void setReport(String Report) {
        this.Report = Report;
    }

    public Integer getSignBox() {
        return SignBox != null ? SignBox : 0;
    }

    public void setSignBox(Integer SignBox) {
        this.SignBox = SignBox;
    }

    public Boolean getNextPage() {
        return NextPage != null ? NextPage : false;
    }

    public void setNextPage(Boolean NextPage) {
        this.NextPage = NextPage;
    }

    public Boolean getNextSummary() {
        return NextSummary != null ? NextSummary : false;
    }

    public void setNextSummary(Boolean NextSummary) {
        this.NextSummary = NextSummary;
    }

    public Boolean getToEdit() {
        return ToEdit != null ? ToEdit : false;
    }

    public void setToEdit(Boolean ToEdit) {
        this.ToEdit = ToEdit;
    }

    public Long getRecord_Modified() {
        return Record_Modified != null ? Record_Modified : 0;
    }

    public void setRecord_Modified(Long Record_Modified) {
        this.Record_Modified = Record_Modified;
    }

    public Boolean getRecord_Upload() {
        return Record_Upload != null ? Record_Upload : false;
    }

    public void setRecord_Upload(Boolean Record_Upload) {
        this.Record_Upload = Record_Upload;
    }

}
