package aero.pilotlog.databases.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table IMAGE_PIC.
 */
public class ImagePic {

    private byte[] ImgCode;
    private byte[] LinkCode;
    private String FileName;
    private String ImgURL;
    private Long Record_Modified;
    private Boolean Record_Upload;

    public ImagePic() {
    }

    public ImagePic(byte[] ImgCode) {
        this.ImgCode = ImgCode;
    }

    public ImagePic(byte[] ImgCode, byte[] LinkCode, String FileName, String ImgURL, Long Record_Modified, Boolean Record_Upload) {
        this.ImgCode = ImgCode;
        this.LinkCode = LinkCode;
        this.FileName = FileName;
        this.ImgURL = ImgURL;
        this.Record_Modified = Record_Modified;
        this.Record_Upload = Record_Upload;
    }

    public byte[] getImgCode() {
        return ImgCode;
    }

    public void setImgCode(byte[] ImgCode) {
        this.ImgCode = ImgCode;
    }

    public byte[] getLinkCode() {
        return LinkCode;
    }

    public void setLinkCode(byte[] LinkCode) {
        this.LinkCode = LinkCode;
    }

    public String getFileName() {
        return FileName;
    }

    public void setFileName(String FileName) {
        this.FileName = FileName;
    }

    public String getImgURL() {
        return ImgURL;
    }

    public void setImgURL(String ImgURL) {
        this.ImgURL = ImgURL;
    }

    public Long getRecord_Modified() {
        return Record_Modified;
    }

    public void setRecord_Modified(Long Record_Modified) {
        this.Record_Modified = Record_Modified;
    }

    public Boolean getRecord_Upload() {
        return Record_Upload;
    }

    public void setRecord_Upload(Boolean Record_Upload) {
        this.Record_Upload = Record_Upload;
    }

}
