package aero.pilotlog.databases.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MY_QUERY.
 */
public class MyQuery {

    private byte[] mQCode;
    private String ShortName;
    private String Name;
    private Boolean QuickView;
    private Long Record_Modified;
    private Boolean Record_Upload;

    public MyQuery() {
    }

    public MyQuery(byte[] mQCode) {
        this.mQCode = mQCode;
    }

    public MyQuery(byte[] mQCode, String ShortName, String Name, Boolean QuickView, Long Record_Modified, Boolean Record_Upload) {
        this.mQCode = mQCode;
        this.ShortName = ShortName;
        this.Name = Name;
        this.QuickView = QuickView;
        this.Record_Modified = Record_Modified;
        this.Record_Upload = Record_Upload;
    }

    public byte[] getMQCode() {
        return mQCode;
    }

    public void setMQCode(byte[] mQCode) {
        this.mQCode = mQCode;
    }

    public String getShortName() {
        return ShortName;
    }

    public void setShortName(String ShortName) {
        this.ShortName = ShortName;
    }

    public String getName() {
        return Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

    public Boolean getQuickView() {
        return QuickView;
    }

    public void setQuickView(Boolean QuickView) {
        this.QuickView = QuickView;
    }

    public Long getRecord_Modified() {
        return Record_Modified;
    }

    public void setRecord_Modified(Long Record_Modified) {
        this.Record_Modified = Record_Modified;
    }

    public Boolean getRecord_Upload() {
        return Record_Upload;
    }

    public void setRecord_Upload(Boolean Record_Upload) {
        this.Record_Upload = Record_Upload;
    }

}
