package aero.pilotlog.databases.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MY_QUERY_BUILD.
 */
public class MyQueryBuild {

    private byte[] mQBCode;
    private byte[] mQCode;
    private String Build1;
    private Integer Build2;
    private Integer Build3;
    private String Build4;
    private Long Record_Modified;
    private Boolean Record_Upload;

    public MyQueryBuild() {
    }

    public MyQueryBuild(byte[] mQBCode) {
        this.mQBCode = mQBCode;
    }

    public MyQueryBuild(byte[] mQBCode, byte[] mQCode, String Build1, Integer Build2, Integer Build3, String Build4, Long Record_Modified, Boolean Record_Upload) {
        this.mQBCode = mQBCode;
        this.mQCode = mQCode;
        this.Build1 = Build1;
        this.Build2 = Build2;
        this.Build3 = Build3;
        this.Build4 = Build4;
        this.Record_Modified = Record_Modified;
        this.Record_Upload = Record_Upload;
    }

    public byte[] getMQBCode() {
        return mQBCode;
    }

    public void setMQBCode(byte[] mQBCode) {
        this.mQBCode = mQBCode;
    }

    public byte[] getMQCode() {
        return mQCode;
    }

    public void setMQCode(byte[] mQCode) {
        this.mQCode = mQCode;
    }

    public String getBuild1() {
        return Build1;
    }

    public void setBuild1(String Build1) {
        this.Build1 = Build1;
    }

    public Integer getBuild2() {
        return Build2;
    }

    public void setBuild2(Integer Build2) {
        this.Build2 = Build2;
    }

    public Integer getBuild3() {
        return Build3;
    }

    public void setBuild3(Integer Build3) {
        this.Build3 = Build3;
    }

    public String getBuild4() {
        return Build4;
    }

    public void setBuild4(String Build4) {
        this.Build4 = Build4;
    }

    public Long getRecord_Modified() {
        return Record_Modified;
    }

    public void setRecord_Modified(Long Record_Modified) {
        this.Record_Modified = Record_Modified;
    }

    public Boolean getRecord_Upload() {
        return Record_Upload;
    }

    public void setRecord_Upload(Boolean Record_Upload) {
        this.Record_Upload = Record_Upload;
    }

}
