package aero.pilotlog.databases.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PILOT.
 */
public class Pilot {

    private byte[] PilotCode;
    private Boolean Active;
    private String Company;
    private String PilotRef;
    private String PilotName;
    private String PilotSearch;
    private String PilotPhone;
    private String PhoneSearch;
    private String PilotEMail;
    private String Facebook;
    private String LinkedIn;
    private String Certificate;
    private String Notes;
    private String RosterAlias;
    private String airCREWaccount;
    private Long Record_Modified;
    private Boolean Record_Upload;
    private boolean IsSelected = false;

    public Pilot() {
    }

    public Pilot(byte[] PilotCode) {
        this.PilotCode = PilotCode;
    }

    public Pilot(byte[] PilotCode, Boolean Active, String Company, String PilotRef, String PilotName, String PilotSearch, String PilotPhone, String PhoneSearch, String PilotEMail, String Facebook, String LinkedIn, String Certificate, String Notes, String RosterAlias, String airCREWaccount, Long Record_Modified, Boolean Record_Upload) {
        this.PilotCode = PilotCode;
        this.Active = Active;
        this.Company = Company;
        this.PilotRef = PilotRef;
        this.PilotName = PilotName;
        this.PilotSearch = PilotSearch;
        this.PilotPhone = PilotPhone;
        this.PhoneSearch = PhoneSearch;
        this.PilotEMail = PilotEMail;
        this.Facebook = Facebook;
        this.LinkedIn = LinkedIn;
        this.Certificate = Certificate;
        this.Notes = Notes;
        this.RosterAlias = RosterAlias;
        this.airCREWaccount = airCREWaccount;
        this.Record_Modified = Record_Modified;
        this.Record_Upload = Record_Upload;
        this.IsSelected = false;
    }

    public byte[] getPilotCode() {
        return PilotCode;
    }

    public void setPilotCode(byte[] PilotCode) {
        this.PilotCode = PilotCode;
    }

    public Boolean getActive() {
        return Active;
    }

    public void setActive(Boolean Active) {
        this.Active = Active;
    }

    public String getCompany() {
        return Company;
    }

    public void setCompany(String Company) {
        this.Company = Company;
    }

    public String getPilotRef() {
        return PilotRef;
    }

    public void setPilotRef(String PilotRef) {
        this.PilotRef = PilotRef;
    }

    public String getPilotName() {
        return PilotName;
    }

    public void setPilotName(String PilotName) {
        this.PilotName = PilotName;
    }

    public String getPilotSearch() {
        return PilotSearch;
    }

    public void setPilotSearch(String PilotSearch) {
        this.PilotSearch = PilotSearch;
    }

    public String getPilotPhone() {
        return PilotPhone;
    }

    public void setPilotPhone(String PilotPhone) {
        this.PilotPhone = PilotPhone;
    }

    public String getPhoneSearch() {
        return PhoneSearch;
    }

    public void setPhoneSearch(String PhoneSearch) {
        this.PhoneSearch = PhoneSearch;
    }

    public String getPilotEMail() {
        return PilotEMail;
    }

    public void setPilotEMail(String PilotEMail) {
        this.PilotEMail = PilotEMail;
    }

    public String getFacebook() {
        return Facebook;
    }

    public void setFacebook(String Facebook) {
        this.Facebook = Facebook;
    }

    public String getLinkedIn() {
        return LinkedIn;
    }

    public void setLinkedIn(String LinkedIn) {
        this.LinkedIn = LinkedIn;
    }

    public String getCertificate() {
        return Certificate;
    }

    public void setCertificate(String Certificate) {
        this.Certificate = Certificate;
    }

    public String getNotes() {
        return Notes;
    }

    public void setNotes(String Notes) {
        this.Notes = Notes;
    }

    public String getRosterAlias() {
        return RosterAlias;
    }

    public void setRosterAlias(String RosterAlias) {
        this.RosterAlias = RosterAlias;
    }

    public String getAirCREWaccount() {
        return airCREWaccount;
    }

    public void setAirCREWaccount(String airCREWaccount) {
        this.airCREWaccount = airCREWaccount;
    }

    public Long getRecord_Modified() {
        return Record_Modified;
    }

    public void setRecord_Modified(Long Record_Modified) {
        this.Record_Modified = Record_Modified;
    }

    public Boolean getRecord_Upload() {
        return Record_Upload;
    }

    public void setRecord_Upload(Boolean Record_Upload) {
        this.Record_Upload = Record_Upload;
    }

    public boolean isSelected() {
        return IsSelected;
    }

    public void setSelected(boolean selected) {
        IsSelected = selected;
    }
}
