package aero.pilotlog.databases.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table QUALIFICATION.
 */
public class Qualification {

    private byte[] QCode;
    private Integer QTypeCode;
    private Integer Validity;
    private String DateIssued;
    private String DateValid;
    private Integer MinimumQty;
    private Integer MinimumPeriod;
    private String RefModel;
    private byte[] RefAirfield;
    private Integer RefExtra;
    private Integer NotifyDays;
    private String NotifyComment;
    private Long Record_Modified;
    private Boolean Record_Upload;
    private Integer ActualQty;
    private String RefExtraCondition;
    private int ProficiencyUpComingDay;

    public String getStringRefAirfield() {
        return StringRefAirfield;
    }

    public void setStringRefAirfield(String stringRefAirfield) {
        StringRefAirfield = stringRefAirfield;
    }

    private String StringRefAirfield;

    public ZQualification getZQualification() {
        return zQualification;
    }

    public void setZQualification(ZQualification zQualification) {
        this.zQualification = zQualification;
    }

    private ZQualification zQualification;
    public enum QualificationStatus{
        EXPIRED,
        UPCOMING,
        HISTORICAL,
        VALID
    }

    private QualificationStatus Status;

    public Qualification() {
    }

    public Qualification(byte[] QCode) {
        this.QCode = QCode;
    }

    public Qualification(byte[] QCode, Integer QTypeCode, Integer Validity, String DateIssued, String DateValid,
                         Integer MinimumQty, Integer MinimumPeriod, String RefModel, byte[] RefAirfield,
                         Integer RefExtra, Integer NotifyDays, String NotifyComment, Long Record_Modified,
                         Boolean Record_Upload) {
        this.QCode = QCode;
        this.QTypeCode = QTypeCode;
        this.Validity = Validity;
        this.DateIssued = DateIssued;
        this.DateValid = DateValid;
        this.MinimumQty = MinimumQty;
        this.MinimumPeriod = MinimumPeriod;
        this.RefModel = RefModel;
        this.RefAirfield = RefAirfield;
        this.RefExtra = RefExtra;
        this.NotifyDays = NotifyDays;
        this.NotifyComment = NotifyComment;
        this.Record_Modified = Record_Modified;
        this.Record_Upload = Record_Upload;
    }

    public byte[] getQCode() {
        return QCode;
    }

    public void setQCode(byte[] QCode) {
        this.QCode = QCode;
    }

    public Integer getQTypeCode() {
        return QTypeCode;
    }

    public void setQTypeCode(Integer QTypeCode) {
        this.QTypeCode = QTypeCode;
    }

    public Integer getValidity() {
        return Validity;
    }

    public void setValidity(Integer Validity) {
        this.Validity = Validity;
    }

    public String getDateIssued() {
        return DateIssued;
    }

    public void setDateIssued(String DateIssued) {
        this.DateIssued = DateIssued;
    }

    public String getDateValid() {
        return DateValid;
    }

    public void setDateValid(String DateValid) {
        this.DateValid = DateValid;
    }

    public Integer getMinimumQty() {
        return MinimumQty;
    }

    public void setMinimumQty(Integer MinimumQty) {
        this.MinimumQty = MinimumQty;
    }

    public Integer getMinimumPeriod() {
        return MinimumPeriod;
    }

    public void setMinimumPeriod(Integer MinimumPeriod) {
        this.MinimumPeriod = MinimumPeriod;
    }

    public String getRefModel() {
        return RefModel;
    }

    public void setRefModel(String RefModel) {
        this.RefModel = RefModel;
    }

    public byte[] getRefAirfield() {
        return RefAirfield;
    }

    public void setRefAirfield(byte[] RefAirfield) {
        this.RefAirfield = RefAirfield;
    }

    public Integer getRefExtra() {
        return RefExtra;
    }

    public void setRefExtra(Integer RefExtra) {
        this.RefExtra = RefExtra;
    }

    public Integer getNotifyDays() {
        return NotifyDays;
    }

    public void setNotifyDays(Integer NotifyDays) {
        this.NotifyDays = NotifyDays;
    }

    public String getNotifyComment() {
        return NotifyComment;
    }

    public void setNotifyComment(String NotifyComment) {
        this.NotifyComment = NotifyComment;
    }

    public Long getRecord_Modified() {
        return Record_Modified;
    }

    public void setRecord_Modified(Long Record_Modified) {
        this.Record_Modified = Record_Modified;
    }

    public Boolean getRecord_Upload() {
        return Record_Upload;
    }

    public void setRecord_Upload(Boolean Record_Upload) {
        this.Record_Upload = Record_Upload;
    }

   /* public String getQTypeLong() {
        return QTypeLong;
    }

    public void setQTypeLong(String QTypeLong) {
        this.QTypeLong = QTypeLong;
    }*/
    public Integer getActualQty() {
        return ActualQty;
    }

    public void setActualQty(Integer actualQty) {
        ActualQty = actualQty;
    }

    public QualificationStatus getStatus() {
        return Status;
    }

    public void setStatus(QualificationStatus status) {
        Status = status;
    }

    public String getRefExtraCondition() {
        return RefExtraCondition;
    }

    public void setRefExtraCondition(String refExtraCondition) {
        RefExtraCondition = refExtraCondition;
    }

    public int getProficiencyUpComingDay() {
        return ProficiencyUpComingDay;
    }

    public void setProficiencyUpComingDay(int proficiencyUpComingDay) {
        ProficiencyUpComingDay = proficiencyUpComingDay;
    }
}
