package aero.pilotlog.databases.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table RECORD_DELETE.
 */
public class RecordDelete {

    private String TableName;
    private byte[] RecordCode;

    public RecordDelete() {
    }

    public RecordDelete(byte[] RecordCode) {
        this.RecordCode = RecordCode;
    }

    public RecordDelete(String TableName, byte[] RecordCode) {
        this.TableName = TableName;
        this.RecordCode = RecordCode;
    }

    public String getTableName() {
        return TableName;
    }

    public void setTableName(String TableName) {
        this.TableName = TableName;
    }

    public byte[] getRecordCode() {
        return RecordCode;
    }

    public void setRecordCode(byte[] RecordCode) {
        this.RecordCode = RecordCode;
    }

}
