package aero.pilotlog.databases.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SETTING_LOCAL.
 */
public class SettingLocal {

    private Integer ConfigCode;
    private String Group;
    private String Name;
    private String Data;

    public SettingLocal() {
    }

    public SettingLocal(Integer ConfigCode) {
        this.ConfigCode = ConfigCode;
    }

    public SettingLocal(Integer ConfigCode, String Group, String Name, String Data) {
        this.ConfigCode = ConfigCode;
        this.Group = Group;
        this.Name = Name;
        this.Data = Data;
    }

    public Integer getConfigCode() {
        return ConfigCode;
    }

    public void setConfigCode(Integer ConfigCode) {
        this.ConfigCode = ConfigCode;
    }

    public String getGroup() {
        return Group;
    }

    public void setGroup(String Group) {
        this.Group = Group;
    }

    public String getName() {
        return Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

    public String getData() {
        return Data;
    }

    public void setData(String Data) {
        this.Data = Data;
    }

}
