package aero.pilotlog.databases.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SETTING_CONFIG.
 */
public class SettingConfig {

    private Integer ConfigCode;
    private String Group;
    private String Name;
    private String Data;
    private Long Record_Modified;
    private Boolean Record_Upload;

    public SettingConfig() {
    }

    public SettingConfig(Integer ConfigCode) {
        this.ConfigCode = ConfigCode;
    }

    public SettingConfig(Integer ConfigCode, String Group, String Name, String Data, Long Record_Modified, Boolean Record_Upload) {
        this.ConfigCode = ConfigCode;
        this.Group = Group;
        this.Name = Name;
        this.Data = Data;
        this.Record_Modified = Record_Modified;
        this.Record_Upload = Record_Upload;
    }

    public Integer getConfigCode() {
        return ConfigCode;
    }

    public void setConfigCode(Integer ConfigCode) {
        this.ConfigCode = ConfigCode;
    }

    public String getGroup() {
        return Group;
    }

    public void setGroup(String Group) {
        this.Group = Group;
    }

    public String getName() {
        return Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

    public String getData() {
        return Data;
    }

    public void setData(String Data) {
        this.Data = Data;
    }

    public Long getRecord_Modified() {
        return Record_Modified;
    }

    public void setRecord_Modified(Long Record_Modified) {
        this.Record_Modified = Record_Modified;
    }

    public Boolean getRecord_Upload() {
        return Record_Upload;
    }

    public void setRecord_Upload(Boolean Record_Upload) {
        this.Record_Upload = Record_Upload;
    }

}
