package aero.pilotlog.databases.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table VALIDATION_RULES.
 */
public class ValidationRules {

    private byte[] VCode;
    private Integer VTCode;
    private String VDate;
    private Integer VDays;
    private String VModel;
    private String VComment;
    private Integer VLanding;
    private Integer VLandingPeriod;
    private Integer VCCT;
    private String VExtra;
    private Long Record_Modified;
    private Boolean Record_Upload;

    public ValidationRules() {
    }

    public ValidationRules(byte[] VCode) {
        this.VCode = VCode;
    }

    public ValidationRules(byte[] VCode, Integer VTCode, String VDate, Integer VDays, String VModel, String VComment, Integer VLanding, Integer VLandingPeriod, Integer VCCT, String VExtra, Long Record_Modified, Boolean Record_Upload) {
        this.VCode = VCode;
        this.VTCode = VTCode;
        this.VDate = VDate;
        this.VDays = VDays;
        this.VModel = VModel;
        this.VComment = VComment;
        this.VLanding = VLanding;
        this.VLandingPeriod = VLandingPeriod;
        this.VCCT = VCCT;
        this.VExtra = VExtra;
        this.Record_Modified = Record_Modified;
        this.Record_Upload = Record_Upload;
    }

    public byte[] getVCode() {
        return VCode;
    }

    public void setVCode(byte[] VCode) {
        this.VCode = VCode;
    }

    public Integer getVTCode() {
        return VTCode;
    }

    public void setVTCode(Integer VTCode) {
        this.VTCode = VTCode;
    }

    public String getVDate() {
        return VDate;
    }

    public void setVDate(String VDate) {
        this.VDate = VDate;
    }

    public Integer getVDays() {
        return VDays;
    }

    public void setVDays(Integer VDays) {
        this.VDays = VDays;
    }

    public String getVModel() {
        return VModel;
    }

    public void setVModel(String VModel) {
        this.VModel = VModel;
    }

    public String getVComment() {
        return VComment;
    }

    public void setVComment(String VComment) {
        this.VComment = VComment;
    }

    public Integer getVLanding() {
        return VLanding;
    }

    public void setVLanding(Integer VLanding) {
        this.VLanding = VLanding;
    }

    public Integer getVLandingPeriod() {
        return VLandingPeriod;
    }

    public void setVLandingPeriod(Integer VLandingPeriod) {
        this.VLandingPeriod = VLandingPeriod;
    }

    public Integer getVCCT() {
        return VCCT;
    }

    public void setVCCT(Integer VCCT) {
        this.VCCT = VCCT;
    }

    public String getVExtra() {
        return VExtra;
    }

    public void setVExtra(String VExtra) {
        this.VExtra = VExtra;
    }

    public Long getRecord_Modified() {
        return Record_Modified;
    }

    public void setRecord_Modified(Long Record_Modified) {
        this.Record_Modified = Record_Modified;
    }

    public Boolean getRecord_Upload() {
        return Record_Upload;
    }

    public void setRecord_Upload(Boolean Record_Upload) {
        this.Record_Upload = Record_Upload;
    }

}
