package aero.pilotlog.databases.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table WEATHER_LOCAL.
 */
public class WeatherLocal {

    private String AFIcao;
    private String AFIata;
    private String Report;
    private String Icon;
    private String DateSaved;
    private String AFName;
    private String AFCountry;
    private boolean mIsSelected = false;

    public WeatherLocal() {
    }

    public WeatherLocal(String AFIcao) {
        this.AFIcao = AFIcao;
    }

    public WeatherLocal(String AFIcao, String AFIata, String Report, String Icon, String DateSaved, String AFName, String AFCountry) {
        this.AFIcao = AFIcao;
        this.AFIata = AFIata;
        this.Report = Report;
        this.Icon = Icon;
        this.DateSaved = DateSaved;
        this.AFName = AFName;
        this.AFCountry = AFCountry;
        this.mIsSelected = false;
    }

    public String getAFIcao() {
        return AFIcao;
    }

    public void setAFIcao(String AFIcao) {
        this.AFIcao = AFIcao;
    }

    public String getAFIata() {
        return AFIata;
    }

    public void setAFIata(String AFIata) {
        this.AFIata = AFIata;
    }

    public String getReport() {
        return Report;
    }

    public void setReport(String Report) {
        this.Report = Report;
    }

    public String getIcon() {
        return Icon;
    }

    public void setIcon(String Icon) {
        this.Icon = Icon;
    }

    public String getDateSaved() {
        return DateSaved;
    }

    public void setDateSaved(String DateSaved) {
        this.DateSaved = DateSaved;
    }

    public String getAFName() {
        return AFName;
    }

    public void setAFName(String AFName) {
        this.AFName = AFName;
    }

    public String getAFCountry() {
        return AFCountry;
    }

    public void setAFCountry(String AFCountry) {
        this.AFCountry = AFCountry;
    }
    public boolean isSelected() {
        return mIsSelected;
    }

    public void setSelected(boolean mIsSelected) {
        this.mIsSelected = mIsSelected;
    }

}
