package aero.pilotlog.databases.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table WEATHER_AF.
 */
public class WeatherAF {

    private byte[] WxAFCode;
    private byte[] WxCode;
    private byte[] AFCode;
    private Long Record_Modified;
    private Boolean Record_Upload;

    public WeatherAF() {
    }

    public WeatherAF(byte[] WxAFCode) {
        this.WxAFCode = WxAFCode;
    }

    public WeatherAF(byte[] WxAFCode, byte[] WxCode, byte[] AFCode, Long Record_Modified, Boolean Record_Upload) {
        this.WxAFCode = WxAFCode;
        this.WxCode = WxCode;
        this.AFCode = AFCode;
        this.Record_Modified = Record_Modified;
        this.Record_Upload = Record_Upload;
    }

    public byte[] getWxAFCode() {
        return WxAFCode;
    }

    public void setWxAFCode(byte[] WxAFCode) {
        this.WxAFCode = WxAFCode;
    }

    public byte[] getWxCode() {
        return WxCode;
    }

    public void setWxCode(byte[] WxCode) {
        this.WxCode = WxCode;
    }

    public byte[] getAFCode() {
        return AFCode;
    }

    public void setAFCode(byte[] AFCode) {
        this.AFCode = AFCode;
    }

    public Long getRecord_Modified() {
        return Record_Modified;
    }

    public void setRecord_Modified(Long Record_Modified) {
        this.Record_Modified = Record_Modified;
    }

    public Boolean getRecord_Upload() {
        return Record_Upload;
    }

    public void setRecord_Upload(Boolean Record_Upload) {
        this.Record_Upload = Record_Upload;
    }

}
