package aero.pilotlog.databases.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ZAPPROACH_CAT.
 */
public class ZApproachCat {

    private Integer APCat;
    private String APCatShort;
    private String APCatLong;
    private Long Record_Modified;

    public ZApproachCat() {
    }

    public ZApproachCat(Integer APCat) {
        this.APCat = APCat;
    }

    public ZApproachCat(Integer APCat, String APCatShort, String APCatLong, Long Record_Modified) {
        this.APCat = APCat;
        this.APCatShort = APCatShort;
        this.APCatLong = APCatLong;
        this.Record_Modified = Record_Modified;
    }

    public Integer getAPCat() {
        return APCat;
    }

    public void setAPCat(Integer APCat) {
        this.APCat = APCat;
    }

    public String getAPCatShort() {
        return APCatShort;
    }

    public void setAPCatShort(String APCatShort) {
        this.APCatShort = APCatShort;
    }

    public String getAPCatLong() {
        return APCatLong;
    }

    public void setAPCatLong(String APCatLong) {
        this.APCatLong = APCatLong;
    }

    public Long getRecord_Modified() {
        return Record_Modified;
    }

    public void setRecord_Modified(Long Record_Modified) {
        this.Record_Modified = Record_Modified;
    }

}
