package aero.pilotlog.databases.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ZCURRENCY.
 */
public class ZCurrency {

    private Integer CurrCode;
    private String CurrShort;
    private String CurrLong;
    private Long ConversionRate;
    private Long Record_Modified;

    public ZCurrency() {
    }

    public ZCurrency(Integer CurrCode) {
        this.CurrCode = CurrCode;
    }

    public ZCurrency(Integer CurrCode, String CurrShort, String CurrLong, Long ConversionRate, Long Record_Modified) {
        this.CurrCode = CurrCode;
        this.CurrShort = CurrShort;
        this.CurrLong = CurrLong;
        this.ConversionRate = ConversionRate;
        this.Record_Modified = Record_Modified;
    }

    public Integer getCurrCode() {
        return CurrCode;
    }

    public void setCurrCode(Integer CurrCode) {
        this.CurrCode = CurrCode;
    }

    public String getCurrShort() {
        return CurrShort;
    }

    public void setCurrShort(String CurrShort) {
        this.CurrShort = CurrShort;
    }

    public String getCurrLong() {
        return CurrLong;
    }

    public void setCurrLong(String CurrLong) {
        this.CurrLong = CurrLong;
    }

    public Long getConversionRate() {
        return ConversionRate;
    }

    public void setConversionRate(Long ConversionRate) {
        this.ConversionRate = ConversionRate;
    }

    public Long getRecord_Modified() {
        return Record_Modified;
    }

    public void setRecord_Modified(Long Record_Modified) {
        this.Record_Modified = Record_Modified;
    }

}
