package aero.pilotlog.databases.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.util.Log;

import me.yokeyword.indexablerv.IndexableEntity;

/**
 * Entity mapped to table ZDELAY.
 */
public class ZDelay implements IndexableEntity {

    private Integer DelayCode;
    private String DelayDD;
    private String DelayShort;
    private String DelayLong;
    private Integer DelayGroupCode;
    private Long Record_Modified;

    public String getDelayGroup() {
        return DelayGroup;
    }

    public void setDelayGroup(String delayGroup) {
        DelayGroup = delayGroup;
    }

    private String DelayGroup;

    public ZDelay() {
    }

    public ZDelay(Integer DelayCode) {
        this.DelayCode = DelayCode;
    }

    public ZDelay(Integer DelayCode, String DelayDD, String DelayShort, String DelayLong, Integer DelayGroupCode, Long Record_Modified) {
        this.DelayCode = DelayCode;
        this.DelayDD = DelayDD;
        this.DelayShort = DelayShort;
        this.DelayLong = DelayLong;
        this.DelayGroupCode = DelayGroupCode;
        this.Record_Modified = Record_Modified;
    }

    public Integer getDelayCode() {
        return DelayCode;
    }

    public void setDelayCode(Integer DelayCode) {
        this.DelayCode = DelayCode;
    }

    public String getDelayDD() {
        return DelayDD;
    }

    public void setDelayDD(String DelayDD) {
        this.DelayDD = DelayDD;
    }

    public String getDelayShort() {
        return DelayShort;
    }

    public void setDelayShort(String DelayShort) {
        this.DelayShort = DelayShort;
    }

    public String getDelayLong() {
        return DelayLong;
    }

    public void setDelayLong(String DelayLong) {
        this.DelayLong = DelayLong;
    }

    public Integer getDelayGroupCode() {
        return DelayGroupCode;
    }

    public void setDelayGroupCode(Integer DelayGroupCode) {
        this.DelayGroupCode = DelayGroupCode;
    }

    public Long getRecord_Modified() {
        return Record_Modified;
    }

    public void setRecord_Modified(Long Record_Modified) {
        this.Record_Modified = Record_Modified;
    }

    @Override
    public String getFieldIndexBy() {
        //Log.d("delay group", getDelayGroup());
        return getDelayGroup();
    }

    @Override
    public void setFieldIndexBy(String indexField) {
        //setDelayGroup(indexField);
    }

    @Override
    public void setFieldPinyinIndexBy(String pinyin) {
        //setDelayGroup(pinyin);
    }
}
