package aero.pilotlog.databases.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ZDELAY_GROUP.
 */
public class ZDelayGroup {

    private Integer DelayGroupCode;
    private String DelayGG;
    private String DelayGroupName;
    private Long Record_Modified;

    public ZDelayGroup() {
    }

    public ZDelayGroup(Integer DelayGroupCode) {
        this.DelayGroupCode = DelayGroupCode;
    }

    public ZDelayGroup(Integer DelayGroupCode, String DelayGG, String DelayGroupName, Long Record_Modified) {
        this.DelayGroupCode = DelayGroupCode;
        this.DelayGG = DelayGG;
        this.DelayGroupName = DelayGroupName;
        this.Record_Modified = Record_Modified;
    }

    public Integer getDelayGroupCode() {
        return DelayGroupCode;
    }

    public void setDelayGroupCode(Integer DelayGroupCode) {
        this.DelayGroupCode = DelayGroupCode;
    }

    public String getDelayGG() {
        return DelayGG;
    }

    public void setDelayGG(String DelayGG) {
        this.DelayGG = DelayGG;
    }

    public String getDelayGroupName() {
        return DelayGroupName;
    }

    public void setDelayGroupName(String DelayGroupName) {
        this.DelayGroupName = DelayGroupName;
    }

    public Long getRecord_Modified() {
        return Record_Modified;
    }

    public void setRecord_Modified(Long Record_Modified) {
        this.Record_Modified = Record_Modified;
    }

}
