package aero.pilotlog.databases.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ZEXPENSE_GROUP.
 */
public class ZExpenseGroup {

    private Integer ExpGroupCode;
    private String ExpGroupShort;
    private String ExpGroupLong;
    private Long Record_Modified;

    public ZExpenseGroup() {
    }

    public ZExpenseGroup(Integer ExpGroupCode) {
        this.ExpGroupCode = ExpGroupCode;
    }

    public ZExpenseGroup(Integer ExpGroupCode, String ExpGroupShort, String ExpGroupLong, Long Record_Modified) {
        this.ExpGroupCode = ExpGroupCode;
        this.ExpGroupShort = ExpGroupShort;
        this.ExpGroupLong = ExpGroupLong;
        this.Record_Modified = Record_Modified;
    }

    public Integer getExpGroupCode() {
        return ExpGroupCode;
    }

    public void setExpGroupCode(Integer ExpGroupCode) {
        this.ExpGroupCode = ExpGroupCode;
    }

    public String getExpGroupShort() {
        return ExpGroupShort;
    }

    public void setExpGroupShort(String ExpGroupShort) {
        this.ExpGroupShort = ExpGroupShort;
    }

    public String getExpGroupLong() {
        return ExpGroupLong;
    }

    public void setExpGroupLong(String ExpGroupLong) {
        this.ExpGroupLong = ExpGroupLong;
    }

    public Long getRecord_Modified() {
        return Record_Modified;
    }

    public void setRecord_Modified(Long Record_Modified) {
        this.Record_Modified = Record_Modified;
    }

}
