package aero.pilotlog.databases.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ZEXPENSE.
 */
public class ZExpense {

    private Integer ETCode;
    private Boolean Debit;
    private String ExpTypeShort;
    private String ExpTypeLong;
    private Integer ExpGroupCode;
    private Integer MostUsed;
    private Long Record_Modified;

    public ZExpense() {
    }

    public ZExpense(Integer ETCode) {
        this.ETCode = ETCode;
    }

    public ZExpense(Integer ETCode, Boolean Debit, String ExpTypeShort, String ExpTypeLong, Integer ExpGroupCode, Integer MostUsed, Long Record_Modified) {
        this.ETCode = ETCode;
        this.Debit = Debit;
        this.ExpTypeShort = ExpTypeShort;
        this.ExpTypeLong = ExpTypeLong;
        this.ExpGroupCode = ExpGroupCode;
        this.MostUsed = MostUsed;
        this.Record_Modified = Record_Modified;
    }

    public Integer getETCode() {
        return ETCode;
    }

    public void setETCode(Integer ETCode) {
        this.ETCode = ETCode;
    }

    public Boolean getDebit() {
        return Debit;
    }

    public void setDebit(Boolean Debit) {
        this.Debit = Debit;
    }

    public String getExpTypeShort() {
        return ExpTypeShort;
    }

    public void setExpTypeShort(String ExpTypeShort) {
        this.ExpTypeShort = ExpTypeShort;
    }

    public String getExpTypeLong() {
        return ExpTypeLong;
    }

    public void setExpTypeLong(String ExpTypeLong) {
        this.ExpTypeLong = ExpTypeLong;
    }

    public Integer getExpGroupCode() {
        return ExpGroupCode;
    }

    public void setExpGroupCode(Integer ExpGroupCode) {
        this.ExpGroupCode = ExpGroupCode;
    }

    public Integer getMostUsed() {
        return MostUsed;
    }

    public void setMostUsed(Integer MostUsed) {
        this.MostUsed = MostUsed;
    }

    public Long getRecord_Modified() {
        return Record_Modified;
    }

    public void setRecord_Modified(Long Record_Modified) {
        this.Record_Modified = Record_Modified;
    }

}
