package aero.pilotlog.databases.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ZLAUNCH.
 */
public class ZLaunch {

    private Integer LaunchCode;

    public String getLaunchLL() {
        return LaunchLL;
    }

    public void setLaunchLL(String launchLL) {
        LaunchLL = launchLL;
    }

    private String LaunchLL;
    private String LaunchShort;
    private String LaunchLong;
    private Long Record_Modified;

    public ZLaunch() {
    }

    public ZLaunch(Integer LaunchCode) {
        this.LaunchCode = LaunchCode;
    }

    public ZLaunch(Integer LaunchCode, String LaunchLL, String LaunchShort, String LaunchLong, Long Record_Modified) {
        this.LaunchLL = LaunchLL;
        this.LaunchCode = LaunchCode;
        this.LaunchShort = LaunchShort;
        this.LaunchLong = LaunchLong;
        this.Record_Modified = Record_Modified;
    }

    public Integer getLaunchCode() {
        return LaunchCode;
    }

    public void setLaunchCode(Integer LaunchCode) {
        this.LaunchCode = LaunchCode;
    }

    public String getLaunchShort() {
        return LaunchShort;
    }

    public void setLaunchShort(String LaunchShort) {
        this.LaunchShort = LaunchShort;
    }

    public String getLaunchLong() {
        return LaunchLong;
    }

    public void setLaunchLong(String LaunchLong) {
        this.LaunchLong = LaunchLong;
    }

    public Long getRecord_Modified() {
        return Record_Modified;
    }

    public void setRecord_Modified(Long Record_Modified) {
        this.Record_Modified = Record_Modified;
    }

}
