package aero.pilotlog.databases.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ZLIMIT.
 */
public class ZLimit {

    private Integer LPeriodCode;
    private String LPeriodLong;
    private Long Record_Modified;

    public ZLimit() {
    }

    public ZLimit(Integer LPeriodCode) {
        this.LPeriodCode = LPeriodCode;
    }

    public ZLimit(Integer LPeriodCode, String LPeriodLong, Long Record_Modified) {
        this.LPeriodCode = LPeriodCode;
        this.LPeriodLong = LPeriodLong;
        this.Record_Modified = Record_Modified;
    }

    public Integer getLPeriodCode() {
        return LPeriodCode;
    }

    public void setLPeriodCode(Integer LPeriodCode) {
        this.LPeriodCode = LPeriodCode;
    }

    public String getLPeriodLong() {
        return LPeriodLong;
    }

    public void setLPeriodLong(String LPeriodLong) {
        this.LPeriodLong = LPeriodLong;
    }

    public Long getRecord_Modified() {
        return Record_Modified;
    }

    public void setRecord_Modified(Long Record_Modified) {
        this.Record_Modified = Record_Modified;
    }

}
