package aero.pilotlog.databases.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ZQUALIFICATION.
 */
public class ZQualification {

    private Integer QTypeCode;
    private String QTypeLong;
    private Boolean IsCertificate;
    private String MinimumWord1;
    private String MinimumWord2;
    private Boolean ReqModel;
    private Boolean ReqAirfield;
    private Boolean ReqExtra;
    private Long Record_Modified;

    public ZQualification() {
    }

    public ZQualification(Integer QTypeCode) {
        this.QTypeCode = QTypeCode;
    }

    public ZQualification(Integer QTypeCode, String QTypeLong, Boolean IsCertificate, String MinimumWord1, String MinimumWord2, Boolean ReqModel, Boolean ReqAirfield, Boolean ReqExtra, Long Record_Modified) {
        this.QTypeCode = QTypeCode;
        this.QTypeLong = QTypeLong;
        this.IsCertificate = IsCertificate;
        this.MinimumWord1 = MinimumWord1;
        this.MinimumWord2 = MinimumWord2;
        this.ReqModel = ReqModel;
        this.ReqAirfield = ReqAirfield;
        this.ReqExtra = ReqExtra;
        this.Record_Modified = Record_Modified;
    }

    public Integer getQTypeCode() {
        return QTypeCode;
    }

    public void setQTypeCode(Integer QTypeCode) {
        this.QTypeCode = QTypeCode;
    }

    public String getQTypeLong() {
        return QTypeLong;
    }

    public void setQTypeLong(String QTypeLong) {
        this.QTypeLong = QTypeLong;
    }

    public Boolean getIsCertificate() {
        return IsCertificate;
    }

    public void setIsCertificate(Boolean IsCertificate) {
        this.IsCertificate = IsCertificate;
    }

    public String getMinimumWord1() {
        return MinimumWord1;
    }

    public void setMinimumWord1(String MinimumWord1) {
        this.MinimumWord1 = MinimumWord1;
    }

    public String getMinimumWord2() {
        return MinimumWord2;
    }

    public void setMinimumWord2(String MinimumWord2) {
        this.MinimumWord2 = MinimumWord2;
    }

    public Boolean getReqModel() {
        return ReqModel;
    }

    public void setReqModel(Boolean ReqModel) {
        this.ReqModel = ReqModel;
    }

    public Boolean getReqAirfield() {
        return ReqAirfield;
    }

    public void setReqAirfield(Boolean ReqAirfield) {
        this.ReqAirfield = ReqAirfield;
    }

    public Boolean getReqExtra() {
        return ReqExtra;
    }

    public void setReqExtra(Boolean ReqExtra) {
        this.ReqExtra = ReqExtra;
    }

    public Long getRecord_Modified() {
        return Record_Modified;
    }

    public void setRecord_Modified(Long Record_Modified) {
        this.Record_Modified = Record_Modified;
    }

}
