package aero.pilotlog.databases.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ZTIME_ZONE.
 */
public class ZTimeZone {

    private Integer TZCode;
    private String TimeZone;
    private String ZoneShort;
    private String ZoneLong;
    private String DSTCode;
    private Long Record_Modified;

    public ZTimeZone() {
    }

    public ZTimeZone(Integer TZCode) {
        this.TZCode = TZCode;
    }

    public ZTimeZone(Integer TZCode, String TimeZone, String ZoneShort, String ZoneLong, String DSTCode, Long Record_Modified) {
        this.TZCode = TZCode;
        this.TimeZone = TimeZone;
        this.ZoneShort = ZoneShort;
        this.ZoneLong = ZoneLong;
        this.DSTCode = DSTCode;
        this.Record_Modified = Record_Modified;
    }

    public Integer getTZCode() {
        return TZCode;
    }

    public void setTZCode(Integer TZCode) {
        this.TZCode = TZCode;
    }

    public String getTimeZone() {
        return TimeZone;
    }

    public void setTimeZone(String TimeZone) {
        this.TimeZone = TimeZone;
    }

    public String getZoneShort() {
        return ZoneShort;
    }

    public void setZoneShort(String ZoneShort) {
        this.ZoneShort = ZoneShort;
    }

    public String getZoneLong() {
        return ZoneLong;
    }

    public void setZoneLong(String ZoneLong) {
        this.ZoneLong = ZoneLong;
    }

    public String getDSTCode() {
        return DSTCode;
    }

    public void setDSTCode(String DSTCode) {
        this.DSTCode = DSTCode;
    }

    public Long getRecord_Modified() {
        return Record_Modified;
    }

    public void setRecord_Modified(Long Record_Modified) {
        this.Record_Modified = Record_Modified;
    }

}
