package aero.pilotlog.databases.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ZTIME_ZONE_DST.
 */
public class ZTimeZoneDST {

    private String DSTCode;
    private String Rule;
    private Long Record_Modified;

    public ZTimeZoneDST() {
    }

    public ZTimeZoneDST(String DSTCode) {
        this.DSTCode = DSTCode;
    }

    public ZTimeZoneDST(String DSTCode, String Rule, Long Record_Modified) {
        this.DSTCode = DSTCode;
        this.Rule = Rule;
        this.Record_Modified = Record_Modified;
    }

    public String getDSTCode() {
        return DSTCode;
    }

    public void setDSTCode(String DSTCode) {
        this.DSTCode = DSTCode;
    }

    public String getRule() {
        return Rule;
    }

    public void setRule(String Rule) {
        this.Rule = Rule;
    }

    public Long getRecord_Modified() {
        return Record_Modified;
    }

    public void setRecord_Modified(Long Record_Modified) {
        this.Record_Modified = Record_Modified;
    }

}
