package aero.pilotlog.databases.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ZVALIDATION.
 */
public class ZValidation {

    private Integer VTCode;
    private String VTerm;
    private Long Record_Modified;

    public ZValidation() {
    }

    public ZValidation(Integer VTCode) {
        this.VTCode = VTCode;
    }

    public ZValidation(Integer VTCode, String VTerm, Long Record_Modified) {
        this.VTCode = VTCode;
        this.VTerm = VTerm;
        this.Record_Modified = Record_Modified;
    }

    public Integer getVTCode() {
        return VTCode;
    }

    public void setVTCode(Integer VTCode) {
        this.VTCode = VTCode;
    }

    public String getVTerm() {
        return VTerm;
    }

    public void setVTerm(String VTerm) {
        this.VTerm = VTerm;
    }

    public Long getRecord_Modified() {
        return Record_Modified;
    }

    public void setRecord_Modified(Long Record_Modified) {
        this.Record_Modified = Record_Modified;
    }

}
